### ISSUE TITLE
RuntimeException - Freeze in EDT - CDF App

### ISSUE THREAD

**Issue by arik-dig** [digma-ai/digma-intellij-plugin#1047]
**Platform:** Intellij IDEA Community
**Version :** 2023.1.5

```
Freeze in EDT for 15 seconds
IDE KILLED! Sampled time: 9100ms, sampling rate: 100ms, GC time: 13ms (0%), Class loading: 0%

com.intellij.diagnostic.Freeze
	at app/jcef/org.cef.CefApp.N_Initialize(Native Method)
	at app/jcef/org.cef.CefApp$3.lambda$run$0(CefApp.java:452)
	at app/jcef/org.cef.CefApp$3$$Lambda$5897/0x00000003027cf5d8.call(Unknown Source)
	at app/jcef/com.jetbrains.cef.JdkEx$InvokeOnToolkitHelperAccessor.invokeAndBlock(JdkEx.java:46)
	at app/jcef/org.cef.CefApp$3.run(CefApp.java:451)
	at app/jcef/org.cef.CefApp.initialize(CefApp.java:463)
	at app/jcef/org.cef.CefApp.createClient(CefApp.java:334)
	at com.intellij.ui.jcef.JBCefApp.createClient(JBCefApp.java:486)
	at com.intellij.ui.jcef.JBCefBrowserBase.lambda$new$3(JBCefBrowserBase.java:157)
	at com.intellij.ui.jcef.JBCefBrowserBase$$Lambda$5894/0x00000003029e6580.create(Unknown Source)
	at com.intellij.util.ObjectUtils.notNull(ObjectUtils.java:123)
	at com.intellij.ui.jcef.JBCefBrowserBase.<init>(JBCefBrowserBase.java:157)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:189)
	at com.intellij.ui.jcef.JBCefBrowser.create(JBCefBrowser.java:140)
	at com.intellij.ui.jcef.JBCefBrowserBuilder.build(JBCefBrowserBuilder.java:127)
	at org.digma.intellij.plugin.assets.AssetsService.<init>(AssetsService.java:59)
	at java.base@17.0.7/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base@17.0.7/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base@17.0.7/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base@17.0.7/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base@17.0.7/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1007)
	at com.intellij.serviceContainer.ComponentManagerImpl.createLightService(ComponentManagerImpl.kt:970)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:774)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:726)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:670)
	at org.digma.intellij.plugin.assets.AssetsService.getInstance(AssetsService.java:130)
	at org.digma.intellij.plugin.assets.AssetsPanel.<init>(AssetsPanel.java:17)
	at org.digma.intellij.plugin.ui.common.HomePanel.createAssetsPanel(HomePanel.kt:43)
	at org.digma.intellij.plugin.ui.common.HomePanel.<init>(HomePanel.kt:34)
	at org.digma.intellij.plugin.ui.common.ContentPanel.<init>(ContentPanel.kt:18)
	at org.digma.intellij.plugin.toolwindow.DigmaSidePaneToolWindowFactory.createToolWindowContent(DigmaSidePaneToolWindowFactory.java:65)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:548)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:527)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:983)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:920)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:906)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1094)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.registerToolWindows(ToolWindowSetInitializer.kt:176)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$registerToolWindows(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1.invokeSuspend(ToolWindowSetInitializer.kt:125)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:829)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at com.intellij.openapi.application.impl.FlushQueue$$Lambda$638/0x0000000300711e88.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base@17.0.7/java.security.AccessController.executePrivileged(AccessController.java:776)
	at java.base@17.0.7/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base@17.0.7/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:571)
	at com.intellij.ide.IdeEventQueue$$Lambda$499/0x00000003006422e0.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1444)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:571)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueueKt$$Lambda$496/0x000000030063bc48.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueue$$Lambda$494/0x000000030063d050.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:829)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by shaykeren** [comment]
cannot reproduce
