### ISSUE TITLE
user ended with 2 instances of Digma backend installed and port conflicts

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#1221]
check the following user full events history for more details:
https://app.posthog.com/person/5d6d483c#activeTab=events

Eventually, the user ended with 2 instances of Digma backend installed and port conflicts.

The process the user went through:

1. The plugin got Engine.up.error (check the exception below)
2. Eventually Digma backend was up and running.
3. The user got updat backend notification
4. user clicks update
5. Digma shows the user the option to download docker-compose file
6. The user installed docker-compose and had issues with port conflicts (ended with 2 Digma backend installations)

notify Roni when this task is resolved, so he can update the user on this one

**2023-08-25T09:46:55.241Z**  Engine.up.start
**2023-08-25T10:01:55.706Z**  Engine.up.error

java.lang.IllegalThreadStateException: process has not exited
	at java.base/java.lang.ProcessImpl.exitValue(ProcessImpl.java:560)
	at org.digma.intellij.plugin.docker.Engine.executeCommand(Engine.kt:200)
	at org.digma.intellij.plugin.docker.Engine.executeCommandWithRetry(Engine.kt:118)
	at org.digma.intellij.plugin.docker.Engine.up(Engine.kt:35)
	at org.digma.intellij.plugin.docker.DockerService.installEngine$lambda$2(DockerService.kt:153)
	at org.digma.intellij.plugin.common.Backgroundable$2.run(Backgroundable.java:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**2023-08-25T10:02:03.368Z**		failed in removeEngine java.nio.file.FileSystemException: C:\Users\Lenovo\AppData\Local\Temp\digma-docker: The process cannot access the file because it is being used by another process
	
**2023-08-25T10:07:54.782Z**	connection first-established

**Comment by shalom938** [comment]
@shaykeren @doppleware 

I think the user flow was:

- auto installation started.
- docker-compose up didn't finish after 15 minutes. process.exitValue() was called and through an exception that we didn't catch, but the end result is the same even if we caught it, the docker-compose up failed and installEngine failed. (this is now fixed and the exception is caught and will provide better posthog message that installEngine failed).
- after installEngine failed we trigger removeEngine to shut down any containers that may have started. removeEngine calls docker-compose down.
- docker-compose down succeeds, but deleting the compose file failed because windows still holds it, the delete happened 1 millisecond after the down process finished and probably windows didn't release the file yet. so we report to posthog that removeEngine failed with exception saying that the file can't be deleted. this is now improved and the code retries to delete the file 5 times with 100 millis delay, if it can't delete report to posthog but from the plugin perspective the local engine is removed.
- the docker service reports to installation wizard that installEngine failed, installation wizard will open the installation options tab with the manual install instructions focused.
- user follows the instructions and install digma manually and after 5 minutes there is connection.
- after some time user gets an update notification and follows the update instructions to download a new docker compose file, he downloads the compose file to a different folder then where he did on first install and runs docker-compose up and gets port already in used.
