### ISSUE TITLE
better handling of AnalyticsServiceException in timers

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-intellij-plugin#1273]
we have many timers that query the backend ever 10 seconds.
when there is no connection all these timers will get an AnalyticsServiceException and report it to ErrorReporter.
it causes too any errors reporting. 
AnalyticsServiceException is reported by the AnalyticsService so there is no need to report it from all these timers.
the timers can ignore AnalyticsServiceException when its a connection exception, but still report other AnalyticsServiceExceptions that may be with the specific API they query

this for example
org.digma.intellij.plugin.analytics.AnalyticsServiceException: An AnalyticsProviderException was caught
	at org.digma.intellij.plugin.analytics.AnalyticsService.executeCatching(AnalyticsService.java:451)
	at org.digma.intellij.plugin.analytics.AnalyticsService.getUnreadNotificationsCount(AnalyticsService.java:412)
	at org.digma.intellij.plugin.ui.notifications.NotificationsService.hasUnreadNotifications(NotificationsService.kt:49)
	at org.digma.intellij.plugin.ui.toolwindow.ToolWindowBadgeChanger.checkUnreadNotifications(ToolWindowBadgeChanger.kt:48)
	at org.digma.intellij.plugin.ui.toolwindow.ToolWindowBadgeChanger.access$checkUnreadNotifications(ToolWindowBadgeChanger.kt:24)
	at org.digma.intellij.plugin.ui.toolwindow.ToolWindowBadgeChanger$runActivity$1.invokeSuspend(ToolWindowBadgeChanger.kt:36)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: org.digma.intellij.plugin.analytics.AnalyticsProviderException: java.net.SocketTimeoutException: timeout
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.execute(RestAnalyticsProvider.java:230)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.getUnreadNotificationsCount(RestAnalyticsProvider.java:197)
	at jdk.internal.reflect.GeneratedMethodAccessor1027.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.digma.intellij.plugin.analytics.AnalyticsService$AnalyticsInvocationHandler.invoke(AnalyticsService.java:535)
	at jdk.proxy9/jdk.proxy9.$Proxy170.getUnreadNotificationsCount(Unknown Source)
	at org.digma.intellij.plugin.analytics.AnalyticsService.lambda$getUnreadNotificationsCount$23(AnalyticsService.java:412)
	at org.digma.intellij.plugin.analytics.AnalyticsService.executeCatching(AnalyticsService.java:449)
	... 11 more
Caused by: java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:678)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:686)
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:154)
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.execute(RestAnalyticsProvider.java:228)
	... 19 more

**Comment by shalom938** [comment]
another example

org.digma.intellij.plugin.analytics.AnalyticsServiceException: UndeclaredThrowableException caught
	at org.digma.intellij.plugin.analytics.AnalyticsService.executeCatching(AnalyticsService.java:453)
	at org.digma.intellij.plugin.analytics.AnalyticsService.getPerformanceMetrics(AnalyticsService.java:418)
	at org.digma.intellij.plugin.posthog.FirstTimePerformanceMetricsMonitor$runActivity$1$1.invokeSuspend(FirstTimePerformanceMetricsMonitor.kt:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: org.digma.intellij.plugin.analytics.AnalyticsServiceException: java.lang.reflect.InvocationTargetException
	at org.digma.intellij.plugin.analytics.AnalyticsService$AnalyticsInvocationHandler.invoke(AnalyticsService.java:576)
	at jdk.proxy12/jdk.proxy12.$Proxy160.getPerformanceMetrics(Unknown Source)
	at org.digma.intellij.plugin.analytics.AnalyticsService.lambda$getPerformanceMetrics$24(AnalyticsService.java:418)
	at org.digma.intellij.plugin.analytics.AnalyticsService.executeCatching(AnalyticsService.java:449)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.digma.intellij.plugin.analytics.AnalyticsService$AnalyticsInvocationHandler.invoke(AnalyticsService.java:535)
	... 11 more
Caused by: org.digma.intellij.plugin.analytics.AnalyticsProviderException: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:5051
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.execute(RestAnalyticsProvider.java:230)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.getPerformanceMetrics(RestAnalyticsProvider.java:212)
	... 16 more
Caused by: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:5051
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.execute(RestAnalyticsProvider.java:228)
	... 17 more
Caused by: java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
	... 37 more
