### ISSUE TITLE
error with UsageStatusResult json from backend

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-intellij-plugin#1274]
sometimes the returned json for UsageStatusResult is broken with null values,
it may cause insights panel issues or  environments combo issues

Caused by: org.digma.intellij.plugin.analytics.AnalyticsProviderException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `org.digma.intellij.plugin.model.rest.usage.UsageStatusResult`, problem: Parameter specified as non-null is null: method org.digma.intellij.plugin.model.rest.usage.UsageStatusResult.<init>, parameter codeObjectStatuses

java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor183.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.digma.intellij.plugin.analytics.AnalyticsService$AnalyticsInvocationHandler.invoke(AnalyticsService.java:533)
	at jdk.proxy4/jdk.proxy4.$Proxy140.getUsageStatus(Unknown Source)
	at org.digma.intellij.plugin.analytics.AnalyticsService.lambda$getUsageStatus$13(AnalyticsService.java:345)
	at org.digma.intellij.plugin.analytics.AnalyticsService.executeCatching(AnalyticsService.java:447)
	at org.digma.intellij.plugin.analytics.AnalyticsService.getUsageStatus(AnalyticsService.java:344)
	at org.digma.intellij.plugin.document.DocumentInfoContainer.loadAllInsightsForCurrentDocument(DocumentInfoContainer.java:105)
	at org.digma.intellij.plugin.document.DocumentInfoContainer.updateCache(DocumentInfoContainer.java:83)
	at org.digma.intellij.plugin.refreshInsightsTask.RefreshService.updateInsightsCacheForActiveDocument(RefreshService.kt:114)
	at org.digma.intellij.plugin.refreshInsightsTask.RefreshService.refreshAllForCurrentFile(RefreshService.kt:59)
	at org.digma.intellij.plugin.refreshInsightsTask.RefreshService$refreshAllForCurrentFile$1.invokeSuspend(RefreshService.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: org.digma.intellij.plugin.analytics.AnalyticsProviderException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `org.digma.intellij.plugin.model.rest.usage.UsageStatusResult`, problem: Parameter specified as non-null is null: method org.digma.intellij.plugin.model.rest.usage.UsageStatusResult.<init>, parameter codeObjectStatuses
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 54]
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.execute(RestAnalyticsProvider.java:210)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.getUsageStatus(RestAnalyticsProvider.java:145)
	... 24 more
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `org.digma.intellij.plugin.model.rest.usage.UsageStatusResult`, problem: Parameter specified as non-null is null: method org.digma.intellij.plugin.model.rest.usage.UsageStatusResult.<init>, parameter codeObjectStatuses
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 54]
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1732)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:491)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:514)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:285)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:198)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:422)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1719)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1244)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:33)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.execute(RestAnalyticsProvider.java:208)
	... 25 more
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method org.digma.intellij.plugin.model.rest.usage.UsageStatusResult.<init>, parameter codeObjectStatuses
	at org.digma.intellij.plugin.model.rest.usage.UsageStatusResult.<init>(UsageStatusResult.kt)
	at jdk.internal.reflect.GeneratedConstructorAccessor158.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283)
	... 38 more

**Comment by shalom938** [comment]
@arik-dig 
can you help here?  it seems that UsageStatusResult.codeObjectStatuses is sometimes null, it has a bad impact. can you help understand why the API sometimes returns null in this field/?

**Comment by arik-dig** [comment]
> @arik-dig can you help here? it seems that UsageStatusResult.codeObjectStatuses is sometimes null, it has a bad impact. can you help understand why the API sometimes returns null in this field/?

@shalom938 ,
i took a look at backend and not sure how could it be null.

anyway, in this case, since those are lists (JSON arrays),
we better put them OUT of the constructor and use JsonProperty

**Comment by shalom938** [comment]
> anyway, in this case, since those are lists (JSON arrays),
> we better put them OUT of the constructor and use JsonProperty

@arik-dig 
This will only push the problem to somewhere else. the field is non-null and treated as non-null where used

**Comment by shalom938** [comment]
can't reproduce
