### ISSUE TITLE
null pointer in MethodUnderCaretDetector.cs in Rider

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-intellij-plugin#1276]
com.jetbrains.rd.util.reactive.RdFault: Object reference not set to an instance of an object., reason: System.NullReferenceException: Object reference not set to an instance of an object.
   at JetBrains.DocumentManagers.Transactions.TextRangeExtensions.CreateDocumentRange(TextRange textRange, IProjectFile projectFile)
   at Digma.Rider.Protocol.MethodUnderCaretDetector.GetTreeNodeUnderCaret(IPsiSourceFile psiSourceFile, IProjectFile projectFile, Int32 offset) in /home/runner/work/digma-intellij-plugin/digma-intellij-plugin/rider/Digma.Rider.Plugin/Digma.Rider/Protocol/MethodUnderCaretDetector.cs:line 250
   at Digma.Rider.Protocol.MethodUnderCaretDetector.GetFunctionUnderCaret(IPsiSourceFile psiSourceFile, MethodUnderCaretRequest methodUnderCaretRequest) in /home/runner/work/digma-intellij-plugin/digma-intellij-plugin/rider/Digma.Rider.Plugin/Digma.Rider/Protocol/MethodUnderCaretDetector.cs:line 206
   at Digma.Rider.Protocol.MethodUnderCaretDetector.<>c__DisplayClass9_1.<DetectByPsiFile>b__0() in /home/runner/work/digma-intellij-plugin/digma-intellij-plugin/rider/Digma.Rider.Plugin/Digma.Rider/Protocol/MethodUnderCaretDetector.cs:line 145
   at Digma.Rider.Protocol.MethodUnderCaretDetector.DetectByPsiFile(MethodUnderCaretRequest methodUnderCaretRequest) in /home/runner/work/digma-intellij-plugin/digma-intellij-plugin/rider/Digma.Rider.Plugin/Digma.Rider/Protocol/MethodUnderCaretDetector.cs:line 142
   at Digma.Rider.Protocol.MethodUnderCaretDetector.Detect(MethodUnderCaretRequest methodUnderCaretRequest) in /home/runner/work/digma-intellij-plugin/digma-intellij-plugin/rider/Digma.Rider.Plugin/Digma.Rider/Protocol/MethodUnderCaretDetector.cs:line 53
   at Digma.Rider.Protocol.LanguageServiceHost.DetectMethodUnderCaret(Lifetime _, MethodUnderCaretRequest methodUnderCaretRequest) in /home/runner/work/digma-intellij-plugin/digma-intellij-plugin/rider/Digma.Rider.Plugin/Digma.Rider/Protocol/LanguageServiceHost.cs:line 137
   at JetBrains.Rd.Tasks.RdCall`2.<>c__DisplayClass24_0.<OnWireReceived>b__0()
	at com.jetbrains.rd.framework.RdTaskResult$Companion.read(TaskInterfaces.kt:30)
	at com.jetbrains.rd.framework.impl.CallSiteWiredRdTask.onWireReceived(RdTask.kt:109)
	at com.jetbrains.rd.framework.impl.WiredRdTask.onWireReceived(RdTask.kt:67)
	at com.jetbrains.rd.framework.MessageBroker.dispatchImpl(MessageBroker.kt:94)
	at com.jetbrains.rd.framework.MessageBroker.dispatch(MessageBroker.kt:74)
	at com.jetbrains.rd.framework.SocketWire$Base.readMsg(SocketWire.kt:220)
	at com.jetbrains.rd.framework.SocketWire$Base.receiverProc(SocketWire.kt:186)
	at com.jetbrains.rd.framework.SocketWire$Base.access$receiverProc(SocketWire.kt:75)
	at com.jetbrains.rd.framework.SocketWire$Base$2.invoke(SocketWire.kt:130)
	at com.jetbrains.rd.framework.SocketWire$Base$2.invoke(SocketWire.kt:114)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.util.reactive.OptProperty.set(Property.kt:41)
	at com.jetbrains.rd.framework.SocketWire$Server$thread$1.invoke(SocketWire.kt:510)
	at com.jetbrains.rd.framework.SocketWire$Server$thread$1.invoke(SocketWire.kt:492)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by shalom938** [comment]
see also

com.jetbrains.rd.util.reactive.RdFault: Object reference not set to an instance of an object., reason: System.NullReferenceException: Object reference not set to an instance of an object.
   at JetBrains.DocumentManagers.Transactions.TextRangeExtensions.CreateDocumentRange(TextRange textRange, IProjectFile projectFile)
   at Digma.Rider.Protocol.MethodUnderCaretDetector.GetTreeNodeUnderCaret(IPsiSourceFile psiSourceFile, IProjectFile projectFile, Int32 offset) in /home/runner/work/digma-intellij-plugin/digma-intellij-plugin/rider/Digma.Rider.Plugin/Digma.Rider/Protocol/MethodUnderCaretDetector.cs:line 250
   at Digma.Rider.Protocol.MethodUnderCaretDetector.GetFunctionUnderCaret(IPsiSourceFile psiSourceFile, MethodUnderCaretRequest methodUnderCaretRequest) in /home/runner/work/digma-intellij-plugin/digma-intellij-plugin/rider/Digma.Rider.Plugin/Digma.Rider/Protocol/MethodUnderCaretDetector.cs:line 206
   at Digma.Rider.Protocol.MethodUnderCaretDetector.<>c__DisplayClass9_1.<DetectByPsiFile>b__0() in /home/runner/work/digma-intellij-plugin/digma-intellij-plugin/rider/Digma.Rider.Plugin/Digma.Rider/Protocol/MethodUnderCaretDetector.cs:line 145
   at Digma.Rider.Protocol.MethodUnderCaretDetector.DetectByPsiFile(MethodUnderCaretRequest methodUnderCaretRequest) in /home/runner/work/digma-intellij-plugin/digma-intellij-plugin/rider/Digma.Rider.Plugin/Digma.Rider/Protocol/MethodUnderCaretDetector.cs:line 142
   at Digma.Rider.Protocol.MethodUnderCaretDetector.Detect(MethodUnderCaretRequest methodUnderCaretRequest) in /home/runner/work/digma-intellij-plugin/digma-intellij-plugin/rider/Digma.Rider.Plugin/Digma.Rider/Protocol/MethodUnderCaretDetector.cs:line 53
   at Digma.Rider.Protocol.LanguageServiceHost.DetectMethodUnderCaret(Lifetime _, MethodUnderCaretRequest methodUnderCaretRequest) in /home/runner/work/digma-intellij-plugin/digma-intellij-plugin/rider/Digma.Rider.Plugin/Digma.Rider/Protocol/LanguageServiceHost.cs:line 137
   at JetBrains.Rd.Tasks.RdCall`2.<>c__DisplayClass24_0.<OnWireReceived>b__0()
	at com.jetbrains.rd.framework.RdTaskResult$Companion.read(TaskInterfaces.kt:30)
	at com.jetbrains.rd.framework.impl.CallSiteWiredRdTask.onWireReceived(RdTask.kt:109)
	at com.jetbrains.rd.framework.impl.WiredRdTask.onWireReceived(RdTask.kt:67)
	at com.jetbrains.rd.framework.MessageBroker.dispatchImpl(MessageBroker.kt:94)
	at com.jetbrains.rd.framework.MessageBroker.dispatch(MessageBroker.kt:74)
	at com.jetbrains.rd.framework.SocketWire$Base.readMsg(SocketWire.kt:220)
	at com.jetbrains.rd.framework.SocketWire$Base.receiverProc(SocketWire.kt:186)
	at com.jetbrains.rd.framework.SocketWire$Base.access$receiverProc(SocketWire.kt:75)
	at com.jetbrains.rd.framework.SocketWire$Base$2.invoke(SocketWire.kt:130)
	at com.jetbrains.rd.framework.SocketWire$Base$2.invoke(SocketWire.kt:114)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.util.reactive.OptProperty.set(Property.kt:41)
	at com.jetbrains.rd.framework.SocketWire$Server$thread$1.invoke(SocketWire.kt:510)
	at com.jetbrains.rd.framework.SocketWire$Server$thread$1.invoke(SocketWire.kt:492)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
