### ISSUE TITLE
null parameter in InsightsOfMethodsResponse

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-intellij-plugin#1280]
impact of this exception may be that insights will not work

java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor143.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.digma.intellij.plugin.analytics.AnalyticsService$AnalyticsInvocationHandler.invoke(AnalyticsService.java:535)
	at jdk.proxy5/jdk.proxy5.$Proxy128.getInsightsOfMethods(Unknown Source)
	at org.digma.intellij.plugin.analytics.AnalyticsService.lambda$getInsightsOfMethods$7(AnalyticsService.java:272)
	at org.digma.intellij.plugin.analytics.AnalyticsService.executeCatching(AnalyticsService.java:449)
	at org.digma.intellij.plugin.analytics.AnalyticsService.getInsightsOfMethods(AnalyticsService.java:272)
	at org.digma.intellij.plugin.document.DocumentInfoContainer.loadInsightsForMethod(DocumentInfoContainer.java:128)
	at org.digma.intellij.plugin.insights.InsightsViewOrchestrator.updateInsightsWithMethodFromSource$lambda$14(InsightsViewOrchestrator.kt:327)
	at org.digma.intellij.plugin.common.Backgroundable.runWithErrorReporting(Backgroundable.java:92)
	at org.digma.intellij.plugin.common.Backgroundable.ensurePooledThread(Backgroundable.java:59)
	at org.digma.intellij.plugin.insights.InsightsViewOrchestrator.updateInsightsWithMethodFromSource(InsightsViewOrchestrator.kt:321)
	at org.digma.intellij.plugin.service.EditorInteractionService.contextChangedImpl(EditorInteractionService.java:134)
	at org.digma.intellij.plugin.service.EditorInteractionService.lambda$contextChanged$0(EditorInteractionService.java:73)
	at org.digma.intellij.plugin.common.Backgroundable.runWithErrorReporting(Backgroundable.java:92)
	at org.digma.intellij.plugin.common.Backgroundable.ensurePooledThread(Backgroundable.java:59)
	at org.digma.intellij.plugin.service.EditorInteractionService.contextChanged(EditorInteractionService.java:69)
	at org.digma.intellij.plugin.editor.EditorEventsHandler.lambda$selectionChangedImpl$2(EditorEventsHandler.java:205)
	at org.digma.intellij.plugin.common.Backgroundable.runWithErrorReporting(Backgroundable.java:92)
	at org.digma.intellij.plugin.common.Backgroundable.lambda$executeOnPooledThread$0(Backgroundable.java:65)
	at com.intellij.codeWithMe.ClientId$Companion.decorateRunnable$lambda$4(ClientId.kt:304)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.digma.intellij.plugin.analytics.AnalyticsProviderException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `org.digma.intellij.plugin.model.rest.insights.InsightsOfMethodsResponse`, problem: Parameter specified as non-null is null: method org.digma.intellij.plugin.model.rest.insights.InsightsOfMethodsResponse.<init>, parameter environment
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 96]
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.execute(RestAnalyticsProvider.java:230)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.getInsightsOfMethods(RestAnalyticsProvider.java:112)
	... 34 more
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `org.digma.intellij.plugin.model.rest.insights.InsightsOfMethodsResponse`, problem: Parameter specified as non-null is null: method org.digma.intellij.plugin.model.rest.insights.InsightsOfMethodsResponse.<init>, parameter environment
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 96]
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1732)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:491)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:514)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:285)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:198)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:422)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1719)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1244)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:33)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.execute(RestAnalyticsProvider.java:228)
	... 35 more
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method org.digma.intellij.plugin.model.rest.insights.InsightsOfMethodsResponse.<init>, parameter environment
	at org.digma.intellij.plugin.model.rest.insights.InsightsOfMethodsResponse.<init>(InsightsOfMethodsResponse.kt)
	at jdk.internal.reflect.GeneratedConstructorAccessor106.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283)
	... 48 more

**Comment by shalom938** [comment]
@arik-dig 
can yo help understand why the environment parameter in InsightsOfMethodsResponse is sometimes null ?

**Comment by arik-dig** [comment]
we echo back from the request:

```
        var response = new InsightOfMethodsResponse()
        {
            AccountId = request.AccountId,
            Environment = request.Environment,
            MethodsWithInsights = methodsWithInsights.ToArray(),
        };

```

**Comment by shalom938** [comment]
closed as can't reproduce
