### ISSUE TITLE
null parameter in LatestCodeObjectEventsResponse

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-intellij-plugin#1281]
the impact is that events will not be loaded from backend

java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor488.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.digma.intellij.plugin.analytics.AnalyticsService$AnalyticsInvocationHandler.invoke(AnalyticsService.java:533)
	at jdk.proxy4/jdk.proxy4.$Proxy140.getLatestEvents(Unknown Source)
	at org.digma.intellij.plugin.analytics.AnalyticsService.lambda$getLatestEvents$5(AnalyticsService.java:246)
	at org.digma.intellij.plugin.analytics.AnalyticsService.executeCatching(AnalyticsService.java:447)
	at org.digma.intellij.plugin.analytics.AnalyticsService.getLatestEvents(AnalyticsService.java:246)
	at org.digma.intellij.plugin.notifications.EventsNotificationsService$waitForEvents$2.invokeSuspend(EventsNotificationsService.kt:66)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: org.digma.intellij.plugin.analytics.AnalyticsProviderException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `org.digma.intellij.plugin.model.rest.event.LatestCodeObjectEventsResponse`, problem: Parameter specified as non-null is null: method org.digma.intellij.plugin.model.rest.event.LatestCodeObjectEventsResponse.<init>, parameter events
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 15]
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.execute(RestAnalyticsProvider.java:210)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.getLatestEvents(RestAnalyticsProvider.java:120)
	... 15 more
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `org.digma.intellij.plugin.model.rest.event.LatestCodeObjectEventsResponse`, problem: Parameter specified as non-null is null: method org.digma.intellij.plugin.model.rest.event.LatestCodeObjectEventsResponse.<init>, parameter events
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 15]
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1732)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:491)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:514)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:285)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:198)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:422)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1719)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1244)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:33)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.execute(RestAnalyticsProvider.java:208)
	... 16 more
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method org.digma.intellij.plugin.model.rest.event.LatestCodeObjectEventsResponse.<init>, parameter events
	at org.digma.intellij.plugin.model.rest.event.LatestCodeObjectEventsResponse.<init>(LatestCodeObjectEventsResponse.kt)
	at jdk.internal.reflect.GeneratedConstructorAccessor165.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283)
	... 29 more

**Comment by shalom938** [comment]
@arik-dig 
can you help understand why the events parameter in LatestCodeObjectEventsResponse is sometimes null?

**Comment by arik-dig** [comment]
looks similar to https://github.com/digma-ai/digma-intellij-plugin/issues/1274#issuecomment-1718846732

lets use JsonProperty

**Comment by shalom938** [comment]
can't reproduce
