### ISSUE TITLE
null parameter in CodeObjectInsightsStatusResponse

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-intellij-plugin#1282]
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor485.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.digma.intellij.plugin.analytics.AnalyticsService$AnalyticsInvocationHandler.invoke(AnalyticsService.java:535)
	at jdk.proxy7/jdk.proxy7.$Proxy145.getCodeObjectInsightStatus(Unknown Source)
	at org.digma.intellij.plugin.analytics.AnalyticsService.lambda$getCodeObjectInsightStatus$9(AnalyticsService.java:294)
	at org.digma.intellij.plugin.analytics.AnalyticsService.executeCatching(AnalyticsService.java:449)
	at org.digma.intellij.plugin.analytics.AnalyticsService.getCodeObjectInsightStatus(AnalyticsService.java:294)
	at org.digma.intellij.plugin.insights.InsightsProvider.getInsightStatus(InsightsProvider.java:71)
	at org.digma.intellij.plugin.ui.service.InsightsViewService.updateInsightsModelWithInsightsProvider$lambda$0(InsightsViewService.kt:189)
	at org.digma.intellij.plugin.common.Backgroundable.runWithErrorReporting(Backgroundable.java:83)
	at org.digma.intellij.plugin.common.Backgroundable$2.run(Backgroundable.java:49)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478)
	at com.intellij.codeWithMe.ClientId$Companion.decorateFunction$lambda$8(ClientId.kt:321)
	at com.intellij.codeWithMe.ClientId$Companion.decorateFunction$lambda$8(ClientId.kt:321)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:477)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.digma.intellij.plugin.analytics.AnalyticsProviderException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `org.digma.intellij.plugin.model.rest.insights.CodeObjectInsightsStatusResponse`, problem: Parameter specified as non-null is null: method org.digma.intellij.plugin.model.rest.insights.CodeObjectInsightsStatusResponse.<init>, parameter environment
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 106]
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.execute(RestAnalyticsProvider.java:230)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.getCodeObjectInsightStatus(RestAnalyticsProvider.java:135)
	... 37 more
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `org.digma.intellij.plugin.model.rest.insights.CodeObjectInsightsStatusResponse`, problem: Parameter specified as non-null is null: method org.digma.intellij.plugin.model.rest.insights.CodeObjectInsightsStatusResponse.<init>, parameter environment
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 106]
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1732)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:491)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:514)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:285)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:198)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:422)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1719)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1244)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:33)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.execute(RestAnalyticsProvider.java:228)
	... 38 more
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method org.digma.intellij.plugin.model.rest.insights.CodeObjectInsightsStatusResponse.<init>, parameter environment
	at org.digma.intellij.plugin.model.rest.insights.CodeObjectInsightsStatusResponse.<init>(CodeObjectInsightsStatusResponse.kt)
	at jdk.internal.reflect.GeneratedConstructorAccessor165.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283)
	... 51 more

**Comment by shalom938** [comment]
@arik-dig 
CodeObjectInsightsStatusResponse., parameter environment is null , can you help ?

**Comment by arik-dig** [comment]
looks similar to https://github.com/digma-ai/digma-intellij-plugin/issues/1274#issuecomment-1718846732

lets use JsonProperty

**Comment by shalom938** [comment]
@arik-dig 
its not similar

**Comment by shalom938** [comment]
can't reproduce
