### ISSUE TITLE
runtime exception NoSuchMethodError - IconLoader.findIcon , at EAP 2023.3

### ISSUE THREAD

**Issue by arik-dig** [digma-ai/digma-intellij-plugin#1381]
Digma plugin version 2.0.187 
Inetllij edition and version: IDEA Community EAP 2023.3 , 233.11361.10

```
com.intellij.diagnostic.PluginException: Cannot init toolwindow org.digma.intellij.plugin.toolwindow.DigmaSidePaneToolWindowFactory@57b83feb [Plugin: org.digma.intellij]
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.registerToolWindows(ToolWindowSetInitializer.kt:233)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$registerToolWindows(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1$1.invokeSuspend(ToolWindowSetInitializer.kt:141)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1$1.invoke(ToolWindowSetInitializer.kt)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1$1.invoke(ToolWindowSetInitializer.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span(tracer.kt:53)
	at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span$default(tracer.kt:49)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1.invokeSuspend(ToolWindowSetInitializer.kt:138)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:857)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:477)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1444)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:862)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.NoSuchMethodError: 'javax.swing.Icon com.intellij.openapi.util.IconLoader.findIcon$default(java.net.URL, boolean, int, java.lang.Object)'
	at org.digma.intellij.plugin.ui.common.SvgIcon.loadSvg(SvgIcon.kt:66)
	at org.digma.intellij.plugin.ui.common.SvgIcon.getIcon(SvgIcon.kt:51)
	at org.digma.intellij.plugin.ui.common.SvgIcon.getIconWidth(SvgIcon.kt:36)
	at java.desktop/javax.swing.SwingUtilities.layoutCompoundLabelImpl(SwingUtilities.java:1091)
	at java.desktop/javax.swing.SwingUtilities.layoutCompoundLabel(SwingUtilities.java:1004)
	at java.desktop/javax.swing.plaf.basic.BasicGraphicsUtils.getPreferredButtonSize(BasicGraphicsUtils.java:362)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaButtonUI.getPreferredSize(DarculaButtonUI.java:309)
	at java.desktop/javax.swing.plaf.basic.BasicButtonUI.getMinimumSize(BasicButtonUI.java:513)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1801)
	at java.desktop/java.awt.GridLayout.minimumLayoutSize(GridLayout.java:392)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at java.desktop/java.awt.BorderLayout.minimumLayoutSize(BorderLayout.java:673)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at java.desktop/java.awt.BorderLayout.minimumLayoutSize(BorderLayout.java:663)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at java.desktop/java.awt.GridLayout.minimumLayoutSize(GridLayout.java:392)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at java.desktop/java.awt.GridBagLayout.GetLayoutInfo(GridBagLayout.java:1113)
	at java.desktop/java.awt.GridBagLayout.getLayoutInfo(GridBagLayout.java:906)
	at java.desktop/java.awt.GridBagLayout.minimumLayoutSize(GridBagLayout.java:740)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at java.desktop/java.awt.CardLayout.minimumLayoutSize(CardLayout.java:320)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at java.desktop/java.awt.BorderLayout.minimumLayoutSize(BorderLayout.java:668)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at java.desktop/java.awt.CardLayout.minimumLayoutSize(CardLayout.java:320)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at java.desktop/java.awt.BorderLayout.minimumLayoutSize(BorderLayout.java:668)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.calculateSize(BasicTabbedPaneUI.java:2705)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.minimumLayoutSize(BasicTabbedPaneUI.java:2679)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at java.desktop/javax.swing.BoxLayout.checkRequests(BoxLayout.java:475)
	at java.desktop/javax.swing.BoxLayout.layoutContainer(BoxLayout.java:417)
	at java.desktop/java.awt.Container.layout(Container.java:1541)
	at java.desktop/java.awt.Container.doLayout(Container.java:1530)
	at java.desktop/java.awt.Container.validateTree(Container.java:1725)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.lambda$validate$3(Container.java:1659)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(SunToolkit.java:2161)
	at java.desktop/java.awt.Container.validate(Container.java:1648)
	at java.desktop/java.awt.CardLayout.show(CardLayout.java:556)
	at org.digma.intellij.plugin.ui.MainToolWindowCardsController.lambda$showCard$4(MainToolWindowCardsController.java:364)
	at org.digma.intellij.plugin.common.EDT.runWithErrorReporting(EDT.java:24)
	at org.digma.intellij.plugin.common.EDT.ensureEDT(EDT.java:16)
	at org.digma.intellij.plugin.ui.MainToolWindowCardsController.showCard(MainToolWindowCardsController.java:364)
	at org.digma.intellij.plugin.ui.MainToolWindowCardsController.showNoConnection(MainToolWindowCardsController.java:354)
	at org.digma.intellij.plugin.ui.MainToolWindowCardsController.initComponents(MainToolWindowCardsController.java:140)
	at org.digma.intellij.plugin.toolwindow.DigmaSidePaneToolWindowFactory.createToolWindowContent(DigmaSidePaneToolWindowFactory.java:99)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:594)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:573)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1035)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:969)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:955)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$registerToolWindow$postTask$1.invoke(ToolWindowManagerImpl.kt:1168)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$registerToolWindow$postTask$1.invoke(ToolWindowManagerImpl.kt:1167)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1181)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.registerToolWindows(ToolWindowSetInitializer.kt:223)
	... 50 more

```

**Comment by shalom938** [comment]
@arik-dig 
can you please give more details? was it a red error popup?
can you reproduce?
I tried to reproduce but can't.
I run the plugin on the same build number but no error like this one.
the error is about missing method that i don't see in any version of intellij so i don't understand it.

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/c1eff6ae-373e-42e4-86de-e0b2280dd9c4)

**Comment by arik-dig** [comment]
@shalom938 

yes - red pop-up

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/5cd48309-fa0a-4659-b791-4ab33ad54e0a)


![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/4c0b094a-a5e5-4ac7-b18e-304cd2059b80)

**Comment by arik-dig** [comment]
i've installed recent EAP version , build 233.11555.11 (2 nov 2023)
and i no longer see the problem
