### ISSUE TITLE
Links from recent activity - sometimes no affect the side panel

### ISSUE THREAD

**Issue by arik-dig** [digma-ai/digma-intellij-plugin#1516]
**Plugin version :** 2.0.219

here's a screen cast of it:

https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/06ec8402-bb6f-46bc-9387-ee114c07e9fd

**Comment by arik-dig** [comment]
@shalom938 
seeing stack trace, I think its related:

```
2023-12-25 11:05:34,301 [  65444]   WARN - #org.digma.intellij.plugin.ui.recentactivity.RecentActivityService - Digma: Project:ktor-sample-kweet: error in processRecentActivityGoToSpanRequest
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606)
	at java.base/java.lang.String.substring(String.java:2709)
	at org.digma.intellij.plugin.idea.psi.kotlin.KotlinLanguageService.findWorkspaceUrisForMethodCodeObjectIds$lambda$6$lambda$5$lambda$4(KotlinLanguageService.kt:85)
	at org.digma.intellij.plugin.common.SlowOperationsUtilsKt.allowSlowOperation(SlowOperationsUtils.kt:39)
	at org.digma.intellij.plugin.idea.psi.kotlin.KotlinLanguageService.findWorkspaceUrisForMethodCodeObjectIds$lambda$6$lambda$5(KotlinLanguageService.kt:84)
	at org.digma.intellij.plugin.common.ReadActions.ensureReadAction(ReadActions.java:34)
	at org.digma.intellij.plugin.idea.psi.kotlin.KotlinLanguageService.findWorkspaceUrisForMethodCodeObjectIds(KotlinLanguageService.kt:83)
	at org.digma.intellij.plugin.navigation.codenavigation.CodeNavigator.canNavigateToMethod$lambda$7$lambda$6(CodeNavigator.kt:118)
	at org.digma.intellij.plugin.common.ReadActions.ensureReadAction(ReadActions.java:14)
	at org.digma.intellij.plugin.navigation.codenavigation.CodeNavigator.canNavigateToMethod(CodeNavigator.kt:117)
	at org.digma.intellij.plugin.navigation.codenavigation.CodeNavigator.canNavigateToSpanOrMethod(CodeNavigator.kt:104)
	at org.digma.intellij.plugin.ui.recentactivity.RecentActivityService.processRecentActivityGoToSpanRequest$lambda$5$lambda$4(RecentActivityService.kt:82)
	at org.digma.intellij.plugin.common.EDT.runWithErrorReporting(EDT.java:24)
	at org.digma.intellij.plugin.common.EDT.lambda$ensureEDT$0(EDT.java:18)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1430)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```
