### ISSUE TITLE
better separation of kotlin plugin classes in dev classpath

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-intellij-plugin#1545]
move all kotlin related services to a separate module so that its not easy to use classes from kotlin plugin in other modules.

also separate in navigation discovery, see this
https://github.com/digma-ai/digma-intellij-plugin/issues/2356

**Comment by shalom938** [comment]
we get errors like this one

java.lang.NoClassDefFoundError: org/jetbrains/kotlin/idea/stubindex/KotlinTopLevelFunctionFqnNameIndex
	at org.digma.intellij.plugin.idea.psi.discovery.endpoint.KtorFrameworkEndpointDiscovery.lookForRoutingBuilderEndpoints$lambda$10$lambda$3(KtorFrameworkEndpointDiscovery.kt:77)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode$lambda$0(DumbService.kt:77)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode$lambda$2(DumbService.kt:129)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.kt:122)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.kt:77)
	at org.digma.intellij.plugin.common.PsiAccessUtilsKt.runInReadAccessInSmartModeWithResultAndRetryIgnorePCE$lambda$5(PsiAccessUtils.kt:65)
	at org.digma.intellij.plugin.common.RetryUtilsKt.runWIthRetryWithResultIgnorePCE(RetryUtils.kt:81)
	at org.digma.intellij.plugin.common.RetryUtilsKt.runWIthRetryWithResultIgnorePCE$default(RetryUtils.kt:70)
	at org.digma.intellij.plugin.common.PsiAccessUtilsKt.runInReadAccessInSmartModeWithResultAndRetryIgnorePCE(PsiAccessUtils.kt:61)
	at org.digma.intellij.plugin.idea.psi.discovery.endpoint.KtorFrameworkEndpointDiscovery.lookForRoutingBuilderEndpoints(KtorFrameworkEndpointDiscovery.kt:75)
	at org.digma.intellij.plugin.idea.psi.discovery.endpoint.KtorFrameworkEndpointDiscovery.lookForEndpoints$lambda$0(KtorFrameworkEndpointDiscovery.kt:58)
	at org.digma.intellij.plugin.common.CatchingUtilsKt.executeCatchingWithRetryIgnorePCE$lambda$0(CatchingUtils.kt:65)
	at org.digma.intellij.plugin.common.RetryUtilsKt.runWIthRetryIgnorePCE(RetryUtils.kt:55)
	at org.digma.intellij.plugin.common.RetryUtilsKt.runWIthRetryIgnorePCE$default(RetryUtils.kt:45)
	at org.digma.intellij.plugin.common.CatchingUtilsKt.executeCatchingWithRetryIgnorePCE(CatchingUtils.kt:64)
	at org.digma.intellij.plugin.common.CatchingUtilsKt.executeCatchingWithRetryIgnorePCE$default(CatchingUtils.kt:62)
	at org.digma.intellij.plugin.idea.psi.discovery.endpoint.KtorFrameworkEndpointDiscovery.lookForEndpoints(KtorFrameworkEndpointDiscovery.kt:57)
	at org.digma.intellij.plugin.idea.navigation.JvmEndpointNavigationProvider.buildEndpointNavigation$lambda$3$lambda$2(JvmEndpointNavigationProvider.kt:68)
	at org.digma.intellij.plugin.idea.navigation.NavigationUtilsKt.executeCatchingWithRetry$lambda$1$lambda$0(navigationUtils.kt:17)
	at org.digma.intellij.plugin.common.RetryUtilsKt.runWIthRetryIgnorePCE(RetryUtils.kt:55)
	at org.digma.intellij.plugin.common.RetryUtilsKt.runWIthRetryIgnorePCE$default(RetryUtils.kt:45)
	at org.digma.intellij.plugin.idea.navigation.NavigationUtilsKt.executeCatchingWithRetry$lambda$1(navigationUtils.kt:16)
	at org.digma.intellij.plugin.common.CatchingUtilsKt.executeCatchingIgnorePCE(CatchingUtils.kt:51)
	at org.digma.intellij.plugin.common.CatchingUtilsKt.executeCatchingIgnorePCE$default(CatchingUtils.kt:49)
	at org.digma.intellij.plugin.idea.navigation.NavigationUtilsKt.executeCatchingWithRetry(navigationUtils.kt:15)
	at org.digma.intellij.plugin.idea.navigation.JvmEndpointNavigationProvider.buildEndpointNavigation(JvmEndpointNavigationProvider.kt:67)
	at org.digma.intellij.plugin.idea.navigation.JvmEndpointNavigationProvider.getTask$lambda$0(JvmEndpointNavigationProvider.kt:47)
	at org.digma.intellij.plugin.idea.navigation.AbstractNavigationDiscovery.buildNavigationUnderProgress$lambda$2(AbstractNavigationDiscovery.kt:117)
	at org.digma.intellij.plugin.progress.InvisibleRetryableTask.run$lambda$0(InvisibleRetryableTask.kt:33)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at org.digma.intellij.plugin.progress.InvisibleRetryableTask.run(InvisibleRetryableTask.kt:32)
	at org.digma.intellij.plugin.progress.ProgressUtilsKt.runInvisibleBackgroundTaskInProgressWithRetry$lambda$0(ProgressUtils.kt:22)
	at org.digma.intellij.plugin.common.Backgroundable.runWithErrorReporting(Backgroundable.java:94)
	at org.digma.intellij.plugin.common.Backgroundable.ensurePooledThread(Backgroundable.java:59)
	at org.digma.intellij.plugin.progress.ProgressUtilsKt.runInvisibleBackgroundTaskInProgressWithRetry(ProgressUtils.kt:21)
	at org.digma.intellij.plugin.progress.RetryableTask$Invisible.runInBackground(RetryableTask.kt:121)
	at org.digma.intellij.plugin.idea.navigation.AbstractNavigationDiscovery.buildNavigationUnderProgress(AbstractNavigationDiscovery.kt:195)
	at org.digma.intellij.plugin.idea.navigation.AbstractNavigationDiscovery.schedule$lambda$1(AbstractNavigationDiscovery.kt:99)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:244)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:222)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.kotlin.idea.stubindex.KotlinTopLevelFunctionFqnNameIndex PluginClassLoader(plugin=PluginDescriptor(name=Digma Continuous Feedback, id=org.digma.intellij, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2023.3\plugins\digma-intellij, version=2.0.311+233, package=null, isBundled=false), packagePrefix=null, state=active)
	... 62 more
