### ISSUE TITLE
gradle or maven plugin may be disabled by the user

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-intellij-plugin#1616]
A user can disable gradle or maven plugin. if that happens our code in OtelRunConfigurationExtension will crash and the agent will not be added to the run configuration.
need to refactor the code in a way that will not crash if any of these plugins is disabled.

**Comment by shaykeren** [comment]
2024-03-22 08:16:58,095 [ 401182]   INFO - #c.i.e.r.ExecutionUtil - Error running 'java in FlexDeployModel2':<br>org/jetbrains/plugins/gradle/service/execution/GradleRunConfiguration
java.lang.NoClassDefFoundError: org/jetbrains/plugins/gradle/service/execution/GradleRunConfiguration
      at org.digma.intellij.plugin.idea.runcfg.RunCfgToolsKt.evalFlavor(RunCfgTools.kt:53)
      at org.digma.intellij.plugin.idea.runcfg.RunCfgToolsKt.tryResolveModule(RunCfgTools.kt:40)
      at org.digma.intellij.plugin.idea.runcfg.RunConfigurationUtilsKt.getWrapperFor(RunConfigurationUtils.kt:28)
      at org.digma.intellij.plugin.idea.runcfg.OtelRunConfigurationExtension.decorate(OtelRunConfigurationExtension.kt:94)
      at com.intellij.execution.JavaRunConfigurationExtensionManager.decorateExecutionConsole(JavaRunConfigurationExtensionManager.kt:52)
      at com.intellij.execution.JavaTestFrameworkRunnableState.execute(JavaTestFrameworkRunnableState.java:276)
      at com.intellij.execution.impl.DefaultJavaProgramRunner.executeJavaState(DefaultJavaProgramRunner.java:181)
      at com.intellij.execution.impl.DefaultJavaProgramRunner.lambda$doExecuteAsync$4(DefaultJavaProgramRunner.java:165)
      at com.intellij.execution.target.TargetEnvironmentAwareRunProfileState$1.run(TargetEnvironmentAwareRunProfileState.java:58)
      at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
      at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
      at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
      at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
      at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
      at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
      at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
      at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
      at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
      at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
      at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
      at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
      at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
      at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
      at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
      at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
      at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
      at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
      at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
      at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:464)
      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
      at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
      at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
      at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
      at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
      at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.plugins.gradle.service.execution.GradleRunConfiguration PluginClassLoader(plugin=PluginDescriptor(name=Digma Continuous Feedback, id=org.digma.intellij, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2023.3\plugins\digma-intellij, version=2.0.303+233, package=null, isBundled=false), packagePrefix=null, state=active)
      ... 36 more
