### ISSUE TITLE
fatal error - psiElement is not instance of requiredClass when calling KotlinFullClassNameIndex.get

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-intellij-plugin#1698]
opened an issue to jetbrains

https://youtrack.jetbrains.com/issue/IDEA-344058/psiElement-is-not-instance-of-requiredClass-when-calling-KotlinFullClassNameIndex.get

java.lang.Throwable: psiElement is not instance of requiredClass.

psiElement=MODIFIER_LIST, psiElement.class=class org.jetbrains.kotlin.psi.KtDeclarationModifierList, requiredClass=class org.jetbrains.kotlin.psi.KtClassOrObject, operation=Looking for io.branch.service.ppp.factory.AwsFactory in org.jetbrains.kotlin.idea.stubindex.KotlinFullClassNameIndex, stubIdList=[138].

ref: 50cf572587cf

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: PSI and index do not match.

Please report the problem to JetBrains with the files attached

file=KtFile: AwsFactory.kt, file.class=class org.jetbrains.kotlin.psi.KtFile, file.lang=Language: kotlin, modStamp=324

tree consistent

stub debugInfo=created in calcStubTree; with backReference

viewProvider=com.intellij.psi.SingleRootFileViewProvider{vFile=file:///Users/\*\*\*\*\*\*\*\*\*\*\*\*\*src/main/kotlin/io/branch/service/ppp/factory/AwsFactory.kt, vFileId=291706, content=VirtualFileContent{size=2157}, eventSystemEnabled=true}

viewProvider stamp: 166945; file stamp: 166945; file modCount: 1706137889595; file length: 2157

doc saved: true; doc stamp: 166945; doc size: 2157; committed: true

indexing info: indexing timestamp = 1705519048816, binary = false, byte size = 2104, char size = 2157

ref: 50cf572587cf

latestIndexedStub=StubTree{myDebugInfo='created from index; with backReference', myRoot=PsiJetFileStubImpl[package=io.branch.service.ppp.factory]}1921207216

same size=false

debugInfo=created from index; with backReference

at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)

at com.intellij.psi.stubs.StubProcessingHelperBase.inconsistencyDetected(StubProcessingHelperBase.java:156)

at com.intellij.psi.stubs.StubProcessingHelperBase.checkType(StubProcessingHelperBase.java:90)

at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:61)

at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$5(StubIndexEx.java:152)

at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:202)

at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:102)

at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:90)

at org.jetbrains.kotlin.idea.stubindex.KotlinStringStubIndexHelper.get(KotlinStringStubIndexHelper.kt:28)

at org.digma.intellij.plugin.idea.psi.kotlin.KotlinLanguageService.findClassByClassName(KotlinLanguageService.kt:68)

at org.digma.intellij.plugin.idea.psi.AbstractJvmLanguageService.findMethodByMethodCodeObjectId$lambda$17$lambda$16(AbstractJvmLanguageService.kt:307)

at org.digma.intellij.plugin.common.SlowOperationsUtilsKt.allowSlowOperation(SlowOperationsUtils.kt:17)

at org.digma.intellij.plugin.idea.psi.AbstractJvmLanguageService.findMethodByMethodCodeObjectId$lambda$17(AbstractJvmLanguageService.kt:306)

at org.digma.intellij.plugin.common.ReadActions.ensureReadAction(ReadActions.java:14)

at org.digma.intellij.plugin.idea.psi.AbstractJvmLanguageService.findMethodByMethodCodeObjectId(AbstractJvmLanguageService.kt:297)

at org.digma.intellij.plugin.idea.psi.AbstractJvmLanguageService$canInstrumentMethod$MyRunnable.run(AbstractJvmLanguageService.kt:471)

at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)

at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:73)

at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:73)

at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)

at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:111)

at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)

at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)

at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)

at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)

at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)

at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)

at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)

at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)

at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)

at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:108)

at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:73)

at com.intellij.openapi.progress.impl.ProgressManagerImpl.runInReadActionWithWriteActionPriority(ProgressManagerImpl.java:182)

at org.digma.intellij.plugin.idea.psi.AbstractJvmLanguageService.canInstrumentMethod$lambda$33(AbstractJvmLanguageService.kt:543)

at org.digma.intellij.plugin.common.Retries.simpleRetryWithResultAndDefault(Retries.java:55)

at org.digma.intellij.plugin.common.Retries.retryWithResultAndDefault(Retries.java:25)

at org.digma.intellij.plugin.idea.psi.AbstractJvmLanguageService.canInstrumentMethod(AbstractJvmLanguageService.kt:540)

at org.digma.intellij.plugin.instrumentation.InstrumentationService.canInstrumentMethod(InstrumentationService.kt:14)

at org.digma.intellij.plugin.instrumentation.MethodInstrumentationPresenter.update(MethodInstrumentationPresenter.kt:37)

at org.digma.intellij.plugin.insights.InsightsServiceImpl.lambda$updateInsightsImpl$8(InsightsServiceImpl.java:323)

at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)

at org.digma.intellij.plugin.insights.InsightsServiceImpl.lambda$updateInsightsImpl$10(InsightsServiceImpl.java:323)

at org.digma.intellij.plugin.insights.InsightsServiceImpl.withUpdateLock(InsightsServiceImpl.java:592)

at org.digma.intellij.plugin.insights.InsightsServiceImpl.lambda$updateInsightsImpl$11(InsightsServiceImpl.java:312)

at org.digma.intellij.plugin.common.Backgroundable.runWithErrorReporting(Backgroundable.java:92)

at org.digma.intellij.plugin.common.Backgroundable.ensurePooledThread(Backgroundable.java:59)

at org.digma.intellij.plugin.insights.InsightsServiceImpl.updateInsightsImpl(InsightsServiceImpl.java:312)

at org.digma.intellij.plugin.insights.InsightsServiceImpl.updateInsights(InsightsServiceImpl.java:295)

at org.digma.intellij.plugin.insights.InsightsViewOrchestrator.showInsightsForMethodFromBackNavigation$lambda$6(InsightsViewOrchestrator.kt:184)

at org.digma.intellij.plugin.common.Backgroundable.runWithErrorReporting(Backgroundable.java:92)

at org.digma.intellij.plugin.common.Backgroundable.lambda$executeOnPooledThread$0(Backgroundable.java:65)

at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)

at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)

at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)

at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)

at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)

at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)

at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by shalom938** [comment]
java.lang.Throwable: psiElement is not instance of requiredClass.
psiElement=PsiImportStatement, psiElement.class=class com.intellij.psi.impl.source.PsiImportStatementImpl, requiredClass=interface com.intellij.psi.PsiClass, operation=Looking for co.altviz.productwheel.coproductionquantitysolver.service.multilevel.sequence.MLSequenceSolverConfigBuilder in java.class.fqn, stubIdList=[45].
ref: 50cf572587cf
com.intellij.psi.stubs.ManyProjectsStubIndexMismatch: PSI and index do not match.
Please report the problem to JetBrains with the files attached
 file=PsiJavaFile:MLSequenceSolverConfigBuilder.java, file.class=class com.intellij.psi.impl.source.PsiJavaFileImpl, file.lang=Language: JAVA, modStamp=21
 tree consistent
 stub debugInfo=created in calcStubTree; with backReference
 viewProvider=com.intellij.psi.SingleRootFileViewProvider{vFile=file:///*****/git/product-wheel-coproduction-quantity-solver/src/main/java/co/altviz/productwheel/coproductionquantitysolver/service/multilevel/sequence/MLSequenceSolverConfigBuilder.java, vFileId=1057, content=VirtualFileContent{size=12530}, eventSystemEnabled=true}
 viewProvider stamp: 15399; file stamp: 509312; file modCount: 1706517990395; file length: 12530
 doc saved: true; doc stamp: 509312; doc size: 12530; committed: false
indexing info: indexing timestamp = 1706517990395, binary = false, byte size = 12530, char size = 12530
ref: 50cf572587cf
latestIndexedStub=null
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.psi.stubs.StubProcessingHelperBase.inconsistencyDetected(StubProcessingHelperBase.java:156)
	at com.intellij.psi.stubs.StubProcessingHelperBase.checkType(StubProcessingHelperBase.java:90)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:61)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$5(StubIndexEx.java:152)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:202)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:102)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:90)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.getClasses(JavaFullClassNameIndex.java:42)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:81)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:104)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:40)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:95)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:73)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:443)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:44)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:378)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:371)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:174)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:234)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:212)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:174)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:855)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:847)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:823)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:426)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:420)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:355)
	at com.intellij.psi.impl.source.PsiImportStatementBaseImpl.resolve(PsiImportStatementBaseImpl.java:61)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.findExplicitDeclarations(PsiJavaFileBaseImpl.java:356)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.lambda$getEnumeratedDeclarations$0(PsiJavaFileBaseImpl.java:340)
	at com.intellij.openapi.util.NotNullLazyValue$4.compute(NotNullLazyValue.java:119)
	at com.intellij.openapi.util.NotNullLazyValue$4.getValue(NotNullLazyValue.java:104)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.lambda$getEnumeratedDeclarations$1(PsiJavaFileBaseImpl.java:341)
	at com.intellij.util.containers.ContainerUtil.process(ContainerUtil.java:812)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:289)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:61)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:40)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:207)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:136)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:492)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:44)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:378)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:371)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:174)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:234)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:212)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:174)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:855)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:847)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:823)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:426)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:420)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:183)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolve(PsiClassReferenceType.java:122)
	at com.intellij.psi.util.TypeConversionUtil$3.visitClassType(TypeConversionUtil.java:1420)
	at com.intellij.psi.util.TypeConversionUtil$3.visitClassType(TypeConversionUtil.java:1411)
	at com.intellij.psi.PsiClassType.accept(PsiClassType.java:225)
	at com.intellij.psi.util.TypeConversionUtil.erasure(TypeConversionUtil.java:1411)
	at com.intellij.psi.util.MethodSignatureUtil.calcErasedParameterTypes(MethodSignatureUtil.java:68)
	at com.intellij.psi.util.MethodSignatureBase.getErasedParameterTypes(MethodSignatureBase.java:78)
	at com.intellij.psi.util.MethodSignatureBase.hashCode(MethodSignatureBase.java:95)
	at com.intellij.psi.util.MethodSignatureUtil$1.hashCode(MethodSignatureUtil.java:22)
	at com.intellij.psi.util.MethodSignatureUtil$1.hashCode(MethodSignatureUtil.java:19)
	at com.intellij.util.containers.CollectionFactory$1.hashCode(CollectionFactory.java:389)
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenCustomHashMap.get(Object2ObjectOpenCustomHashMap.java:345)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.buildMethodHierarchy(PsiSuperMethodImplUtil.java:166)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.lambda$static$1(PsiSuperMethodImplUtil.java:33)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.lambda$getHierarchicalMethodSignature$3(PsiSuperMethodImplUtil.java:408)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.getHierarchicalMethodSignature(PsiSuperMethodImplUtil.java:417)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.getHierarchicalMethodSignature(PsiSuperMethodImplUtil.java:397)
	at com.intellij.psi.impl.source.PsiMethodImpl.getHierarchicalMethodSignature(PsiMethodImpl.java:143)
	at com.intellij.psi.impl.search.MethodSuperSearcher.processQuery(MethodSuperSearcher.java:28)
	at com.intellij.psi.impl.search.MethodSuperSearcher.processQuery(MethodSuperSearcher.java:16)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:76)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:30)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:83)
	at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:100)
	at com.intellij.util.UniqueResultsQuery.processResults(UniqueResultsQuery.java:37)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:83)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.AbstractQuery.findAll(AbstractQuery.java:24)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.findSuperMethodSignatures(PsiSuperMethodImplUtil.java:71)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.findSuperMethodsInternal(PsiSuperMethodImplUtil.java:55)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.findSuperMethods(PsiSuperMethodImplUtil.java:45)
	at com.intellij.psi.impl.source.PsiMethodImpl.findSuperMethods(PsiMethodImpl.java:101)
	at org.digma.intellij.plugin.idea.psi.java.JavaPsiUtils$Companion.findNearestAnnotation(JavaPsiUtils.kt:60)
	at org.digma.intellij.plugin.idea.psi.java.JavaPsiUtils.findNearestAnnotation(JavaPsiUtils.kt)
	at org.digma.intellij.plugin.idea.psi.discovery.endpoint.AbstractJaxrsFramework.lambda$lookForEndpoints$6(AbstractJaxrsFramework.java:153)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode$lambda$2(DumbService.kt:129)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.kt:122)
	at org.digma.intellij.plugin.idea.psi.PsiAccessUtilsKt.runInReadAccess$lambda$0(PsiAccessUtils.kt:12)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at org.digma.intellij.plugin.idea.psi.PsiAccessUtilsKt.runInReadAccess(PsiAccessUtils.kt:11)
	at org.digma.intellij.plugin.idea.psi.discovery.endpoint.AbstractJaxrsFramework.lambda$lookForEndpoints$7(AbstractJaxrsFramework.java:151)
	at org.digma.intellij.plugin.common.Retries.simpleRetry(Retries.java:81)
	at org.digma.intellij.plugin.common.Retries.simpleRetry(Retries.java:16)
	at org.digma.intellij.plugin.idea.psi.discovery.endpoint.AbstractJaxrsFramework.lookForEndpoints(AbstractJaxrsFramework.java:151)
	at org.digma.intellij.plugin.idea.psi.navigation.JavaEndpointNavigationProvider.lambda$buildEndpointForFile$4(JavaEndpointNavigationProvider.java:138)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.digma.intellij.plugin.idea.psi.navigation.JavaEndpointNavigationProvider.buildEndpointForFile(JavaEndpointNavigationProvider.java:135)
	at org.digma.intellij.plugin.idea.psi.navigation.JavaEndpointNavigationProvider.lambda$fileChanged$6(JavaEndpointNavigationProvider.java:200)
	at org.digma.intellij.plugin.common.Backgroundable.runWithErrorReporting(Backgroundable.java:94)
	at org.digma.intellij.plugin.common.Backgroundable.lambda$executeOnPooledThread$0(Backgroundable.java:65)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
