### ISSUE TITLE
error - InconsistencyIndexException: KotlinPartialPackageNamesIndex inconsistency

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-intellij-plugin#1709]
opened issue to jetbrains
https://youtrack.jetbrains.com/issue/KTIJ-28641/InconsistencyIndexException-KotlinPartialPackageNamesIndex-inconsistency

org.jetbrains.kotlin.idea.stubindex.resolve.InconsistencyIndexException: KotlinPartialPackageNamesIndex inconsistency.
Cannot find package fragment 'com.cluster.app.security.config' for file SecurityConfiguration.kt, file package = 'com.cluster.app.security.config':
vFile: file:///Users/elias/Documents/GitLab.nosync/cluster-app/src/main/kotlin/com/cluster/app/security/config/SecurityConfiguration.kt,
nonIndexedFiles = [], isNonIndexed = false,
scope = KotlinSourceFilterScope(delegate=Module-with-dependencies:cluster-app compile-only:false include-libraries:false include-other-modules:false include-tests:false, filter=RootKindFilter(includeProjectSourceFiles=true, includeLibraryClassFiles=false, includeLibrarySourceFiles=false, includeScriptDependencies=false, includeScriptsOutsideSourceRoots=true)), isInScope = true,
packageExists = false, cachedPackageExists = false,
oldPackageExists = false,
SPI.packageExists = false,
OOCB count = 0
moduleModificationCount = 0,
packageFqNameByTree = 'com.cluster.app.security.config', packageDirectiveText = 'package com.cluster.app.security.config'
	at org.jetbrains.kotlin.idea.stubindex.resolve.PluginDeclarationProviderFactory.diagnoseMissingPackageFragmentPartialPackageIndexCorruption(PluginDeclarationProviderFactory.kt:66)
	at org.jetbrains.kotlin.idea.stubindex.resolve.PluginDeclarationProviderFactory.diagnoseMissingPackageFragment(PluginDeclarationProviderFactory.kt:120)
	at org.jetbrains.kotlin.resolve.lazy.ResolveSession.getPackageFragmentOrDiagnoseFailure(ResolveSession.java:275)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeFactory.createScopesForFile(FileScopeFactory.kt:63)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeFactory.createScopesForFile$default(FileScopeFactory.kt:61)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl$cache$1.invoke(FileScopeProvider.kt:48)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl$cache$1.invoke(FileScopeProvider.kt:46)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:681)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl.getFileScopes(FileScopeProvider.kt:53)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProvider.getFileResolutionScope(FileScopeProvider.kt:30)
	at org.jetbrains.kotlin.resolve.lazy.ResolveSession.createAnnotations(ResolveSession.java:243)
	at org.jetbrains.kotlin.resolve.lazy.ResolveSession.lambda$new$0(ResolveSession.java:232)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:681)
	at org.jetbrains.kotlin.resolve.lazy.ResolveSession.getFileAnnotations(ResolveSession.java:379)
	at org.jetbrains.kotlin.idea.project.ResolveElementCache.ensureFileAnnotationsResolved(ResolveElementCache.kt:340)
	at org.jetbrains.kotlin.idea.project.ResolveElementCache.resolveToElement(ResolveElementCache.kt:274)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl$analyze$3.invoke(ModuleResolutionFacadeImpl.kt:53)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl$analyze$3.invoke(ModuleResolutionFacadeImpl.kt:52)
	at com.intellij.openapi.progress.impl.CancellationCheck.withCancellationCheck(CancellationCheck.kt:59)
	at com.intellij.openapi.progress.impl.CancellationCheck$Companion.runWithCancellationCheck(CancellationCheck.kt:105)
	at org.jetbrains.kotlin.idea.util.application.ApplicationUtilsKt.runWithCancellationCheck(ApplicationUtils.kt:63)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl.analyze(ModuleResolutionFacadeImpl.kt:52)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionFacadeWithDebugInfo.analyze(ResolutionFacadeWithDebugInfo.kt:43)
	at org.jetbrains.kotlin.idea.caches.resolve.ExtendedResolutionApiKt.analyze(ExtendedResolutionApi.kt:124)
	at org.jetbrains.kotlin.idea.caches.resolve.ExtendedResolutionApiKt.safeAnalyze(ExtendedResolutionApi.kt:115)
	at org.jetbrains.kotlin.idea.caches.resolve.ExtendedResolutionApiKt.resolveToDescriptorIfAny(ExtendedResolutionApi.kt:56)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionUtils.resolveToDescriptorIfAny(ResolutionUtils.kt:53)
	at org.jetbrains.kotlin.idea.caches.resolve.IDELightClassGenerationSupport.resolveToDescriptor(IDELightClassGenerationSupport.kt:86)
	at org.jetbrains.kotlin.asJava.classes.UltraLightUtilsKt.resolve(ultraLightUtils.kt:155)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.isInternal(ultraLightMembersCreator.kt:422)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.isInternalNonPublishedApi(ultraLightMembersCreator.kt:412)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.computeMethodName(ultraLightMembersCreator.kt:399)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.asJavaMethod(ultraLightMembersCreator.kt:195)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.asJavaMethod$default(ultraLightMembersCreator.kt:182)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.createMethods(ultraLightMembersCreator.kt:128)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.createMethods$default(ultraLightMembersCreator.kt:114)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass.ownMethods(ultraLightClass.kt:277)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass._ownMethods$lambda$7(ultraLightClass.kt:343)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass.getOwnMethods(ultraLightClass.kt:485)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache$methodsCache$1.invoke(KotlinClassInnerStuffCache.kt:60)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache$methodsCache$1.invoke(KotlinClassInnerStuffCache.kt:59)
	at org.jetbrains.kotlin.asJava.classes.LightClassesLazyCreator$get$1$holder$1.invoke$lambda$0(LightClassesLazyCreator.kt:20)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at org.jetbrains.kotlin.asJava.classes.LightClassesLazyCreator$get$1.computeValue(LightClassesLazyCreator.kt:25)
	at org.jetbrains.kotlin.asJava.classes.LightClassesLazyCreator$get$1.getValue(LightClassesLazyCreator.kt:49)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache.getMethods(KotlinClassInnerStuffCache.kt:74)
	at org.jetbrains.kotlin.asJava.classes.KtLightClassBase.getMethods(KtLightClassBase.kt:38)
	at org.jetbrains.uast.kotlin.AbstractKotlinUClass.computeMethods(AbstractKotlinUClass.kt:72)
	at org.jetbrains.uast.kotlin.KotlinUClass.getMethods(KotlinUClass.kt:62)
	at org.digma.intellij.plugin.idea.psi.JvmPsiUtilsKt.getMethodsInClass(JvmPsiUtils.kt:55)
	at org.digma.intellij.plugin.idea.psi.discovery.AbstractCodeObjectDiscovery.collectMethods(AbstractCodeObjectDiscovery.kt:78)
	at org.digma.intellij.plugin.idea.psi.discovery.AbstractCodeObjectDiscovery.buildDocumentInfo(AbstractCodeObjectDiscovery.kt:46)
	at org.digma.intellij.plugin.idea.psi.AbstractJvmLanguageService.buildDocumentInfo$lambda$2$lambda$1$lambda$0(AbstractJvmLanguageService.kt:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at org.digma.intellij.plugin.idea.psi.AbstractJvmLanguageService.buildDocumentInfo$lambda$2$lambda$1(AbstractJvmLanguageService.kt:131)
	at org.digma.intellij.plugin.common.Retries.simpleRetryWithResult(Retries.java:31)
	at org.digma.intellij.plugin.common.Retries.retryWithResult(Retries.java:21)
	at org.digma.intellij.plugin.idea.psi.AbstractJvmLanguageService.buildDocumentInfo$lambda$2(AbstractJvmLanguageService.kt:129)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at org.digma.intellij.plugin.idea.psi.AbstractJvmLanguageService.buildDocumentInfo(AbstractJvmLanguageService.kt:128)
	at org.digma.intellij.plugin.idea.psi.AbstractJvmLanguageService.buildDocumentInfo(AbstractJvmLanguageService.kt:122)
	at org.digma.intellij.plugin.editor.EditorEventsHandler.lambda$selectionChangedImpl$4(EditorEventsHandler.java:175)
	at org.digma.intellij.plugin.common.Backgroundable.runWithErrorReporting(Backgroundable.java:94)
	at org.digma.intellij.plugin.common.Backgroundable.lambda$executeOnPooledThread$0(Backgroundable.java:65)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by shalom938** [comment]
org.jetbrains.kotlin.idea.stubindex.resolve.InconsistencyIndexException: KotlinPartialPackageNamesIndex inconsistency.
Cannot find package fragment 'io.execvision.kworkers' for file KWorkersApplication.kt, file package = 'io.execvision.kworkers':
vFile: file:///home/shane/mf/execvision/javaapis/kworkers/src/main/kotlin/io/execvision/kworkers/KWorkersApplication.kt,
nonIndexedFiles = [], isNonIndexed = false,
scope = KotlinSourceFilterScope(delegate=Module-with-dependencies:kworkers compile-only:false include-libraries:false include-other-modules:false include-tests:false, filter=RootKindFilter(includeProjectSourceFiles=true, includeLibraryClassFiles=false, includeLibrarySourceFiles=false, includeScriptDependencies=false, includeScriptsOutsideSourceRoots=true)), isInScope = true,
packageExists = false, cachedPackageExists = false,
oldPackageExists = false,
SPI.packageExists = false,
OOCB count = 4137
moduleModificationCount = 4137,
packageFqNameByTree = 'io.execvision.kworkers', packageDirectiveText = 'package io.execvision.kworkers'
	at org.jetbrains.kotlin.idea.stubindex.resolve.PluginDeclarationProviderFactory.diagnoseMissingPackageFragmentPartialPackageIndexCorruption(PluginDeclarationProviderFactory.kt:66)
	at org.jetbrains.kotlin.idea.stubindex.resolve.PluginDeclarationProviderFactory.diagnoseMissingPackageFragment(PluginDeclarationProviderFactory.kt:120)
	at org.jetbrains.kotlin.resolve.lazy.ResolveSession.getPackageFragmentOrDiagnoseFailure(ResolveSession.java:275)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeFactory.createScopesForFile(FileScopeFactory.kt:63)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeFactory.createScopesForFile$default(FileScopeFactory.kt:61)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl$cache$1.invoke(FileScopeProvider.kt:48)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl$cache$1.invoke(FileScopeProvider.kt:46)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:681)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProviderImpl.getFileScopes(FileScopeProvider.kt:53)
	at org.jetbrains.kotlin.resolve.lazy.FileScopeProvider.getFileResolutionScope(FileScopeProvider.kt:30)
	at org.jetbrains.kotlin.resolve.lazy.ResolveSession.createAnnotations(ResolveSession.java:243)
	at org.jetbrains.kotlin.resolve.lazy.ResolveSession.lambda$new$0(ResolveSession.java:232)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:681)
	at org.jetbrains.kotlin.resolve.lazy.ResolveSession.getFileAnnotations(ResolveSession.java:379)
	at org.jetbrains.kotlin.idea.project.ResolveElementCache.ensureFileAnnotationsResolved(ResolveElementCache.kt:340)
	at org.jetbrains.kotlin.idea.project.ResolveElementCache.resolveToElement(ResolveElementCache.kt:274)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl$analyze$3.invoke(ModuleResolutionFacadeImpl.kt:53)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl$analyze$3.invoke(ModuleResolutionFacadeImpl.kt:52)
	at com.intellij.openapi.progress.impl.CancellationCheck.withCancellationCheck(CancellationCheck.kt:59)
	at com.intellij.openapi.progress.impl.CancellationCheck$Companion.runWithCancellationCheck(CancellationCheck.kt:105)
	at org.jetbrains.kotlin.idea.util.application.ApplicationUtilsKt.runWithCancellationCheck(ApplicationUtils.kt:63)
	at org.jetbrains.kotlin.idea.caches.resolve.ModuleResolutionFacadeImpl.analyze(ModuleResolutionFacadeImpl.kt:52)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionFacadeWithDebugInfo.analyze(ResolutionFacadeWithDebugInfo.kt:43)
	at org.jetbrains.kotlin.idea.caches.resolve.ExtendedResolutionApiKt.analyze(ExtendedResolutionApi.kt:124)
	at org.jetbrains.kotlin.idea.caches.resolve.ExtendedResolutionApiKt.safeAnalyze(ExtendedResolutionApi.kt:115)
	at org.jetbrains.kotlin.idea.caches.resolve.ExtendedResolutionApiKt.resolveToDescriptorIfAny(ExtendedResolutionApi.kt:56)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionUtils.resolveToDescriptorIfAny(ResolutionUtils.kt:53)
	at org.jetbrains.kotlin.idea.caches.resolve.IDELightClassGenerationSupport.resolveToDescriptor(IDELightClassGenerationSupport.kt:86)
	at org.jetbrains.kotlin.asJava.classes.UltraLightUtilsKt.resolve(ultraLightUtils.kt:155)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.isInternal(ultraLightMembersCreator.kt:422)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.isInternalNonPublishedApi(ultraLightMembersCreator.kt:412)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.computeMethodName(ultraLightMembersCreator.kt:399)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.asJavaMethod(ultraLightMembersCreator.kt:195)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.asJavaMethod$default(ultraLightMembersCreator.kt:182)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.createMethods(ultraLightMembersCreator.kt:128)
	at org.jetbrains.kotlin.asJava.classes.UltraLightMembersCreator.createMethods$default(ultraLightMembersCreator.kt:114)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass.ownMethods(ultraLightClass.kt:277)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass._ownMethods$lambda$7(ultraLightClass.kt:343)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at org.jetbrains.kotlin.asJava.classes.KtUltraLightClass.getOwnMethods(ultraLightClass.kt:485)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache$methodsCache$1.invoke(KotlinClassInnerStuffCache.kt:60)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache$methodsCache$1.invoke(KotlinClassInnerStuffCache.kt:59)
	at org.jetbrains.kotlin.asJava.classes.LightClassesLazyCreator$get$1$holder$1.invoke$lambda$0(LightClassesLazyCreator.kt:20)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at org.jetbrains.kotlin.asJava.classes.LightClassesLazyCreator$get$1.computeValue(LightClassesLazyCreator.kt:25)
	at org.jetbrains.kotlin.asJava.classes.LightClassesLazyCreator$get$1.getValue(LightClassesLazyCreator.kt:49)
	at org.jetbrains.kotlin.asJava.classes.KotlinClassInnerStuffCache.getMethods(KotlinClassInnerStuffCache.kt:74)
	at org.jetbrains.kotlin.asJava.classes.KtLightClassBase.getMethods(KtLightClassBase.kt:38)
	at org.jetbrains.kotlin.asJava.LightClassUtil$getPsiMethodWrappers$2.invoke(LightClassUtil.kt:155)
	at org.jetbrains.kotlin.asJava.LightClassUtil$getPsiMethodWrappers$2.invoke(LightClassUtil.kt:155)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:168)
	at org.jetbrains.kotlin.asJava.LightClassUtil.getPsiMethodWrapper(LightClassUtil.kt:147)
	at org.jetbrains.kotlin.asJava.LightClassUtil.getLightClassMethod(LightClassUtil.kt:128)
	at org.jetbrains.uast.kotlin.BaseKotlinConverter.convertDeclaration(BaseKotlinConverter.kt:185)
	at org.jetbrains.uast.kotlin.BaseKotlinConverter.convertDeclarationOrElement(BaseKotlinConverter.kt:278)
	at org.jetbrains.uast.kotlin.KotlinUastLanguagePlugin.convertElementWithParent(KotlinUastLanguagePlugin.kt:53)
	at org.jetbrains.uast.UastFacade.convertElementWithParent(UastContext.kt:64)
	at org.jetbrains.uast.UastContextKt.toUElement(UastContext.kt:151)
	at org.digma.intellij.plugin.idea.psi.kotlin.KotlinLanguageService.findParentMethod(KotlinLanguageService.kt:197)
	at org.digma.intellij.plugin.idea.psi.AbstractJvmLanguageService.detectMethodUnderCaret(AbstractJvmLanguageService.kt:389)
	at org.digma.intellij.plugin.idea.psi.AbstractJvmLanguageService.detectMethodUnderCaret$lambda$27$lambda$26$lambda$25(AbstractJvmLanguageService.kt:377)
	at org.digma.intellij.plugin.common.SlowOperationsUtilsKt.allowSlowOperation(SlowOperationsUtils.kt:17)
	at org.digma.intellij.plugin.idea.psi.AbstractJvmLanguageService.detectMethodUnderCaret$lambda$27$lambda$26(AbstractJvmLanguageService.kt:371)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at org.digma.intellij.plugin.idea.psi.AbstractJvmLanguageService.detectMethodUnderCaret$lambda$27(AbstractJvmLanguageService.kt:369)
	at org.digma.intellij.plugin.common.Retries.simpleRetryWithResult(Retries.java:31)
	at org.digma.intellij.plugin.common.Retries.simpleRetryWithResult(Retries.java:45)
	at org.digma.intellij.plugin.common.Retries.simpleRetryWithResult(Retries.java:45)
	at org.digma.intellij.plugin.common.Retries.simpleRetryWithResult(Retries.java:45)
	at org.digma.intellij.plugin.common.Retries.simpleRetryWithResult(Retries.java:45)
	at org.digma.intellij.plugin.common.Retries.retryWithResult(Retries.java:21)
	at org.digma.intellij.plugin.idea.psi.AbstractJvmLanguageService.detectMethodUnderCaret(AbstractJvmLanguageService.kt:367)
	at org.digma.intellij.plugin.editor.CurrentContextUpdater.lambda$updateCurrentContext$2(CurrentContextUpdater.java:100)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode$lambda$0(DumbService.kt:77)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode$lambda$2(DumbService.kt:129)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.kt:122)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.kt:77)
	at org.digma.intellij.plugin.editor.CurrentContextUpdater.updateCurrentContext(CurrentContextUpdater.java:100)
	at org.digma.intellij.plugin.editor.CurrentContextUpdater.updateCurrentContext(CurrentContextUpdater.java:93)
	at org.digma.intellij.plugin.editor.CurrentContextUpdater.lambda$addRequest$0(CurrentContextUpdater.java:72)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.util.Alarm$Request.lambda$runSafely$0(Alarm.java:369)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:253)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:369)
	at com.intellij.util.Alarm$Request.run(Alarm.java:356)
	at com.intellij.util.concurrency.Propagation.contextAwareCallable$lambda$2(propagation.kt:357)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:244)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:222)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
