### ISSUE TITLE
fatal error - Argument for @NotNull parameter 'key' of com/intellij/util/containers/RefHashMap.get must not be null

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-intellij-plugin#1746]
git this error from user.
I'm not sure what is the problem but I think we can get rid of all the icons utilities we have. maybe it was necessary when we used swing but we hardly use swing icons.

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'key' of com/intellij/util/containers/RefHashMap.get must not be null
	at com.intellij.util.containers.RefHashMap.$$$reportNull$$$0(RefHashMap.java)
	at com.intellij.util.containers.RefHashMap.get(RefHashMap.java)
	at com.intellij.ui.ExperimentalUIImplKt$createPathPatcher$1.patchPath(ExperimentalUIImpl.kt:308)
	at com.intellij.ui.icons.IconTransform.patchPath(IconTransform.kt:83)
	at com.intellij.ui.icons.ImageDataByUrlLoaderKt.createNewResolverIfNeeded(ImageDataByUrlLoader.kt:147)
	at com.intellij.ui.icons.ImageDataByUrlLoaderKt.access$createNewResolverIfNeeded(ImageDataByUrlLoader.kt:1)
	at com.intellij.ui.icons.ImageDataByUrlLoader.patch(ImageDataByUrlLoader.kt:35)
	at com.intellij.ui.icons.CachedImageIcon.checkPathTransform(CachedImageIcon.kt:181)
	at com.intellij.ui.icons.CachedImageIcon.resolveActualIcon(CachedImageIcon.kt:156)
	at com.intellij.ui.icons.CachedImageIcon.getIconWidth(CachedImageIcon.kt:120)
	at org.digma.intellij.plugin.ui.common.SvgIcon.getIconWidth(SvgIcon.kt:36)
	at java.desktop/javax.swing.SwingUtilities.layoutCompoundLabelImpl(SwingUtilities.java:1091)
	at java.desktop/javax.swing.SwingUtilities.layoutCompoundLabel(SwingUtilities.java:1004)
	at java.desktop/javax.swing.plaf.basic.BasicGraphicsUtils.getPreferredButtonSize(BasicGraphicsUtils.java:362)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaButtonUI.getPreferredSize(DarculaButtonUI.java:309)
	at java.desktop/javax.swing.plaf.basic.BasicButtonUI.getMinimumSize(BasicButtonUI.java:513)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1801)
	at java.desktop/java.awt.GridBagLayout.GetLayoutInfo(GridBagLayout.java:1113)
	at java.desktop/java.awt.GridBagLayout.getLayoutInfo(GridBagLayout.java:906)
	at java.desktop/java.awt.GridBagLayout.minimumLayoutSize(GridBagLayout.java:740)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at com.intellij.ui.dsl.gridLayout.impl.GridImpl.collectPreCalculationData(GridImpl.kt:140)
	at com.intellij.ui.dsl.gridLayout.impl.GridImpl.collectPreCalculationData(GridImpl.kt:146)
	at com.intellij.ui.dsl.gridLayout.impl.GridImpl.collectPreCalculationData(GridImpl.kt:116)
	at com.intellij.ui.dsl.gridLayout.impl.GridImpl.calculatePreferredLayoutData(GridImpl.kt:156)
	at com.intellij.ui.dsl.gridLayout.impl.GridImpl.getPreferredSizeData(GridImpl.kt:71)
	at com.intellij.ui.dsl.gridLayout.GridLayout.getPreferredSizeData$intellij_platform_ide(GridLayout.kt:110)
	at com.intellij.ui.dsl.gridLayout.GridLayout.preferredLayoutSize(GridLayout.kt:66)
	at com.intellij.ui.dsl.gridLayout.GridLayout.minimumLayoutSize(GridLayout.kt:72)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at com.intellij.ui.components.JBPanel.getMinimumSize(JBPanel.java:130)
	at java.desktop/java.awt.GridBagLayout.GetLayoutInfo(GridBagLayout.java:1113)
	at java.desktop/java.awt.GridBagLayout.getLayoutInfo(GridBagLayout.java:906)
	at java.desktop/java.awt.GridBagLayout.minimumLayoutSize(GridBagLayout.java:740)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at java.desktop/java.awt.CardLayout.minimumLayoutSize(CardLayout.java:320)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at java.desktop/java.awt.BorderLayout.minimumLayoutSize(BorderLayout.java:668)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at java.desktop/java.awt.CardLayout.minimumLayoutSize(CardLayout.java:320)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at java.desktop/java.awt.BorderLayout.minimumLayoutSize(BorderLayout.java:668)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.calculateSize(BasicTabbedPaneUI.java:2705)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.minimumLayoutSize(BasicTabbedPaneUI.java:2679)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1803)
	at java.desktop/javax.swing.BoxLayout.checkRequests(BoxLayout.java:475)
	at java.desktop/javax.swing.BoxLayout.layoutContainer(BoxLayout.java:417)
	at java.desktop/java.awt.Container.layout(Container.java:1541)
	at java.desktop/java.awt.Container.doLayout(Container.java:1530)
	at java.desktop/java.awt.Container.validateTree(Container.java:1725)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.lambda$validate$3(Container.java:1659)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(SunToolkit.java:2161)
	at java.desktop/java.awt.Container.validate(Container.java:1648)
	at java.desktop/java.awt.CardLayout.show(CardLayout.java:556)
	at org.digma.intellij.plugin.ui.MainToolWindowCardsController.lambda$showCard$4(MainToolWindowCardsController.java:364)
	at org.digma.intellij.plugin.common.EDT.runWithErrorReporting(EDT.java:24)
	at org.digma.intellij.plugin.common.EDT.ensureEDT(EDT.java:16)
	at org.digma.intellij.plugin.ui.MainToolWindowCardsController.showCard(MainToolWindowCardsController.java:364)
	at org.digma.intellij.plugin.ui.MainToolWindowCardsController.showNoConnection(MainToolWindowCardsController.java:354)
	at org.digma.intellij.plugin.ui.MainToolWindowCardsController.initComponents(MainToolWindowCardsController.java:140)
	at org.digma.intellij.plugin.toolwindow.DigmaSidePaneToolWindowFactory.createToolWindowContent(DigmaSidePaneToolWindowFactory.java:98)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:594)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:573)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1035)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:969)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:955)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$registerToolWindow$postTask$1.invoke(ToolWindowManagerImpl.kt:1168)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$registerToolWindow$postTask$1.invoke(ToolWindowManagerImpl.kt:1167)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1181)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.registerToolWindows(ToolWindowSetInitializer.kt:223)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$registerToolWindows(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1$1.invokeSuspend(ToolWindowSetInitializer.kt:141)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1$1.invoke(ToolWindowSetInitializer.kt)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1$1.invoke(ToolWindowSetInitializer.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span(tracer.kt:53)
	at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span$default(tracer.kt:49)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1.invokeSuspend(ToolWindowSetInitializer.kt:138)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by shalom938** [comment]
second time

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'key' of com/intellij/util/containers/RefHashMap.get must not be null
	at com.intellij.util.containers.RefHashMap.$$$reportNull$$$0(RefHashMap.java)
	at com.intellij.util.containers.RefHashMap.get(RefHashMap.java)
	at com.intellij.ui.ExperimentalUIImplKt$createPathPatcher$1.patchPath(ExperimentalUIImpl.kt:308)
	at com.intellij.ui.icons.IconTransform.patchPath(IconTransform.kt:83)
	at com.intellij.ui.icons.ImageDataByUrlLoaderKt.createNewResolverIfNeeded(ImageDataByUrlLoader.kt:147)
	at com.intellij.ui.icons.ImageDataByUrlLoaderKt.access$createNewResolverIfNeeded(ImageDataByUrlLoader.kt:1)
	at com.intellij.ui.icons.ImageDataByUrlLoader.patch(ImageDataByUrlLoader.kt:35)
	at com.intellij.ui.icons.CachedImageIcon.checkPathTransform(CachedImageIcon.kt:181)
	at com.intellij.ui.icons.CachedImageIcon.resolveActualIcon(CachedImageIcon.kt:156)
	at com.intellij.ui.icons.CachedImageIcon.getIconWidth(CachedImageIcon.kt:120)
	at org.digma.intellij.plugin.ui.common.SvgIcon.getIconWidth(SvgIcon.kt:36)
	at java.desktop/javax.swing.JLabel.setIcon(JLabel.java:414)
	at org.digma.intellij.plugin.ui.common.ScopeLineKt$scopeLine$mainPanel$1.reset(ScopeLine.kt:74)
	at org.digma.intellij.plugin.ui.common.ScopeLinePanel._init_$lambda$2(ScopeLinePanel.kt:45)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:660)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:423)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:402)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:461)
	at jdk.proxy8/jdk.proxy8.$Proxy227.modelChanged(Unknown Source)
	at org.digma.intellij.plugin.ui.service.InsightsViewService.notifyModelChanged(InsightsViewService.kt:364)
	at org.digma.intellij.plugin.ui.service.InsightsViewService.notifyModelChangedAndUpdateUi(InsightsViewService.kt:368)
	at org.digma.intellij.plugin.ui.service.InsightsViewService.updateInsightsModelWithInsightsProvider(InsightsViewService.kt:198)
	at org.digma.intellij.plugin.ui.service.InsightsViewService.updateInsightsModelImpl(InsightsViewService.kt:162)
	at org.digma.intellij.plugin.ui.service.InsightsViewService.updateInsightsModel(InsightsViewService.kt:152)
	at org.digma.intellij.plugin.ui.service.InsightsViewService.updateInsightsModel$default(InsightsViewService.kt:149)
	at org.digma.intellij.plugin.insights.InsightsViewOrchestrator.updateInsightsWithMethodFromSource$lambda$17(InsightsViewOrchestrator.kt:366)
	at org.digma.intellij.plugin.common.Backgroundable.runWithErrorReporting(Backgroundable.java:94)
	at org.digma.intellij.plugin.common.Backgroundable.ensurePooledThread(Backgroundable.java:59)
	at org.digma.intellij.plugin.insights.InsightsViewOrchestrator.updateInsightsWithMethodFromSource(InsightsViewOrchestrator.kt:356)
	at org.digma.intellij.plugin.service.EditorInteractionService.contextChangedImpl(EditorInteractionService.java:134)
	at org.digma.intellij.plugin.service.EditorInteractionService.lambda$contextChanged$0(EditorInteractionService.java:73)
	at org.digma.intellij.plugin.common.Backgroundable.runWithErrorReporting(Backgroundable.java:94)
	at org.digma.intellij.plugin.common.Backgroundable.ensurePooledThread(Backgroundable.java:59)
	at org.digma.intellij.plugin.service.EditorInteractionService.contextChanged(EditorInteractionService.java:69)
	at org.digma.intellij.plugin.editor.CurrentContextUpdater.updateCurrentContext(CurrentContextUpdater.java:113)
	at org.digma.intellij.plugin.editor.CurrentContextUpdater.updateCurrentContext(CurrentContextUpdater.java:95)
	at org.digma.intellij.plugin.editor.CurrentContextUpdater.lambda$addRequest$0(CurrentContextUpdater.java:74)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.util.Alarm$Request.lambda$runSafely$0(Alarm.java:369)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:253)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:369)
	at com.intellij.util.Alarm$Request.run(Alarm.java:356)
	at com.intellij.util.concurrency.Propagation.contextAwareCallable$lambda$2(propagation.kt:357)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:244)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:222)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
