### ISSUE TITLE
Runtime Bug/org.digma.intellij.plugin.psi.PsiFileNotFountException: could not locate VirtualFile for uri

### ISSUE THREAD

**Issue by arik-dig** [digma-ai/digma-intellij-plugin#192]
**Plugin Version**
1.0.41

**Stack trace**
```
org.digma.intellij.plugin.psi.PsiFileNotFountException: could not locate VirtualFile for uri C:\Users\arik\AppData\Local\JetBrains\Rider2022.2\tmp\15084sandbox\a646b12e-308d-4261-86a7-ee131ad622b81699694904688388718.cs
	at org.digma.intellij.plugin.psi.PsiUtils.lambda$uriToPsiFile$0(PsiUtils.java:49)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:941)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at org.digma.intellij.plugin.psi.PsiUtils.uriToPsiFile(PsiUtils.java:46)
	at org.digma.intellij.plugin.rider.protocol.Protocol.normalizeFileUri(protocol.kt:43)
	at org.digma.intellij.plugin.rider.protocol.ElementUnderCaretDetector.toModel(ElementUnderCaretDetector.kt:88)
	at org.digma.intellij.plugin.rider.protocol.ElementUnderCaretDetector.notifyElementUnderCaret(ElementUnderCaretDetector.kt:78)
	at org.digma.intellij.plugin.rider.protocol.ElementUnderCaretDetector.access$notifyElementUnderCaret(ElementUnderCaretDetector.kt:16)
	at org.digma.intellij.plugin.rider.protocol.ElementUnderCaretDetector$2$3.invoke(ElementUnderCaretDetector.kt:47)
	at org.digma.intellij.plugin.rider.protocol.ElementUnderCaretDetector$2$3.invoke(ElementUnderCaretDetector.kt:44)
	at com.jetbrains.rd.util.AdditionalApiKt$throttleLast$1$advise$2$$special$$inlined$schedule$1$lambda$1$1.invoke(AdditionalApi.kt:32)
	at com.jetbrains.rd.util.AdditionalApiKt$throttleLast$1$advise$2$$special$$inlined$schedule$1$lambda$1$1.invoke(AdditionalApi.kt:15)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.executeIfAlive(RLifetime.kt:259)
	at com.jetbrains.rd.util.AdditionalApiKt$throttleLast$1$advise$2$$special$$inlined$schedule$1$lambda$1.invoke(AdditionalApi.kt:31)
	at com.jetbrains.rd.util.AdditionalApiKt$throttleLast$1$advise$2$$special$$inlined$schedule$1$lambda$1.invoke(AdditionalApi.kt:15)
	at com.jetbrains.rd.util.threading.SingleThreadSchedulerBase$queue$1.run(SingleThreadScheduler.kt:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by arik-dig** [comment]
seeing similar stack trace but on properties file:

```
org.digma.intellij.plugin.psi.PsiFileNotFountException: could not locate VirtualFile for uri C:\Users\arik\Documents\GitHub\digma-collector-backend\src\Services\Analytics\Digma.Measurement.Analysis\appsettings.json
	at org.digma.intellij.plugin.psi.PsiUtils.lambda$uriToPsiFile$0(PsiUtils.java:49)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:941)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at org.digma.intellij.plugin.psi.PsiUtils.uriToPsiFile(PsiUtils.java:46)
	at org.digma.intellij.plugin.rider.protocol.Protocol.normalizeFileUri(protocol.kt:43)
	at org.digma.intellij.plugin.rider.protocol.ElementUnderCaretDetector.toModel(ElementUnderCaretDetector.kt:88)
	at org.digma.intellij.plugin.rider.protocol.ElementUnderCaretDetector.notifyElementUnderCaret(ElementUnderCaretDetector.kt:78)
	at org.digma.intellij.plugin.rider.protocol.ElementUnderCaretDetector.access$notifyElementUnderCaret(ElementUnderCaretDetector.kt:16)
	at org.digma.intellij.plugin.rider.protocol.ElementUnderCaretDetector$2$3.invoke(ElementUnderCaretDetector.kt:47)
	at org.digma.intellij.plugin.rider.protocol.ElementUnderCaretDetector$2$3.invoke(ElementUnderCaretDetector.kt:44)
	at com.jetbrains.rd.util.AdditionalApiKt$throttleLast$1$advise$2$$special$$inlined$schedule$1$lambda$1$1.invoke(AdditionalApi.kt:32)
	at com.jetbrains.rd.util.AdditionalApiKt$throttleLast$1$advise$2$$special$$inlined$schedule$1$lambda$1$1.invoke(AdditionalApi.kt:15)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.executeIfAlive(RLifetime.kt:259)
	at com.jetbrains.rd.util.AdditionalApiKt$throttleLast$1$advise$2$$special$$inlined$schedule$1$lambda$1.invoke(AdditionalApi.kt:31)
	at com.jetbrains.rd.util.AdditionalApiKt$throttleLast$1$advise$2$$special$$inlined$schedule$1$lambda$1.invoke(AdditionalApi.kt:15)
	at com.jetbrains.rd.util.threading.SingleThreadSchedulerBase$queue$1.run(SingleThreadScheduler.kt:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by arik-dig** [comment]
its happening repeatedly on all kind of files:
![image](https://user-images.githubusercontent.com/104715391/206491109-84819be2-3fa6-4540-aec0-2dbe676172e1.png)
