### ISSUE TITLE
RuntimeException/com.intellij.openapi.project.IndexNotReadyException: Please change caller according to

### ISSUE THREAD

**Issue by arik-dig** [digma-ai/digma-intellij-plugin#202]
**Plugin Version**
1.0.44

**Stack Trace**

```
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:67)
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:844)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:792)
	at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:350)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:157)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:99)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:87)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:34)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:88)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:111)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:40)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:93)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:71)
	at org.digma.intellij.plugin.idea.psi.java.JavaLanguageService.withSpanAnnotationSpanDiscovery(JavaLanguageService.java:457)
	at org.digma.intellij.plugin.idea.psi.java.JavaLanguageService.spanDiscovery(JavaLanguageService.java:425)
	at org.digma.intellij.plugin.idea.psi.java.JavaLanguageService.lambda$enrichDocumentInfo$3(JavaLanguageService.java:391)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:536)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:206)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by arik-dig** [comment]
I think it happens when I'm editing OpenTelemetry code, which contains reference to annotation `WithSpan`

**Comment by arik-dig** [comment]
@shalom938 , it just happened again with plugin version 1.0.47

**Comment by shalom938** [comment]
@arik-dig i can't see a reason why it should happen and i can't reproduce it in any way.
maybe you can give more details next time, try to set debug logging on, try to remember what you did before it happened , and attache the idea.log.
and maybe you can reopen this bug and move it to in-progress

**Comment by arik-dig** [comment]
@shalom938 try to take this project:
https://github.com/open-telemetry/opentelemetry-java-instrumentation
its quite large but it happens there from time to time.

**Comment by shalom938** [comment]
@arik-dig does it happen with other projects?
if it happens only with the source code of opentelemetry then its probably not urgent, the exception happens when trying to find the WithSpan class and if its the source code them maybe there is some issue with indexing because then its not an external class but a source code class.
and please post the stack trace again because line numbers changed since you last posted it.


And please try to say how important is it that the plugin works correctly with open telemetry source code ? we are searching references to open telementry classes which is kind of weird to do  in the open telemetry source code. if you say that its important then i will think how to fix it, IMO its not so urgent and maybe even not possible. needs investigation.

So the most important question regarding this bug is : does it happen with other projects?

**Comment by arik-dig** [comment]
@shalom938 
I haven't seen it (yet) outside of opentelemetry source code, so I guess we can reduce the priority.
the remaining question is: can you understand or take a guess why does it happen?

**Comment by shalom938** [comment]
Yes, see that the exception happens when calling JavaPsiFacadeImpl.findClass for the WIthSpan class,
my guess is that because WithSpan is not a class reference but a source code file then the API JavaPsiFacadeImpl.findClass has some issues, i don't know what. I'm sure it can be fixed but in some complex way that is probably not necessary.

**Comment by arik-dig** [comment]
@shalom938 it happened again in version 1.0.47 
this time it happened on other project - **NON** OpenTelemetry one.
It did happen while using same workspace with 2 different ide instances - one the standard one, and second is via Run Plugin - and I edit the code from one, and then moved the focus to other window
