### ISSUE TITLE
two urgent errors

### ISSUE THREAD

**Issue by shalom938** [digma-ai/digma-intellij-plugin#2100]
Unhandled exception in [CoroutineId(14497), "coroutine#14497":StandaloneCoroutine{Cancelling}@36e770fb, Dispatchers.Default]

org.digma.intellij.plugin.analytics.AnalyticsServiceException: An AnalyticsProviderException was caught
	at org.digma.intellij.plugin.analytics.AnalyticsService.executeCatching(AnalyticsService.java:539)
	at org.digma.intellij.plugin.analytics.AnalyticsService.getVersions(AnalyticsService.java:307)
	at org.digma.intellij.plugin.updates.AggressiveUpdateService.updateState$lambda$2(AggressiveUpdateService.kt:207)
	at org.digma.intellij.plugin.common.Retries.simpleRetry(Retries.java:81)
	at org.digma.intellij.plugin.common.Retries.simpleRetry(Retries.java:96)
	at org.digma.intellij.plugin.common.Retries.simpleRetry(Retries.java:96)
	at org.digma.intellij.plugin.common.Retries.simpleRetry(Retries.java:96)
	at org.digma.intellij.plugin.common.Retries.simpleRetry(Retries.java:96)
	at org.digma.intellij.plugin.common.Retries.simpleRetry(Retries.java:16)
	at org.digma.intellij.plugin.common.RetryUtilsKt.runWIthRetry(RetryUtils.kt:32)
	at org.digma.intellij.plugin.common.RetryUtilsKt.runWIthRetry$default(RetryUtils.kt:26)
	at org.digma.intellij.plugin.updates.AggressiveUpdateService.updateState(AggressiveUpdateService.kt:204)
	at org.digma.intellij.plugin.updates.AggressiveUpdateService.access$updateState(AggressiveUpdateService.kt:47)
	at org.digma.intellij.plugin.updates.AggressiveUpdateService$4$1.invokeSuspend(AggressiveUpdateService.kt:121)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineId(14497), "coroutine#14497":StandaloneCoroutine{Cancelled}@36e770fb, Dispatchers.Default]
Caused by: org.digma.intellij.plugin.analytics.AnalyticsProviderException: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:5051
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.execute(RestAnalyticsProvider.java:392)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.getVersions(RestAnalyticsProvider.java:205)
	at jdk.internal.reflect.GeneratedMethodAccessor176.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.digma.intellij.plugin.auth.AuthManager$MyAuthInvocationHandler.invoke(AuthManager.kt:470)
	at jdk.proxy7/jdk.proxy7.$Proxy119.getVersions(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor176.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.digma.intellij.plugin.analytics.AnalyticsService$AnalyticsInvocationHandler.invoke(AnalyticsService.java:624)
	at jdk.proxy7/jdk.proxy7.$Proxy119.getVersions(Unknown Source)
	at org.digma.intellij.plugin.analytics.AnalyticsService.lambda$getVersions$17(AnalyticsService.java:307)
	at org.digma.intellij.plugin.analytics.AnalyticsService.executeCatching(AnalyticsService.java:537)
	... 19 more
Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:5051
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:223)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider$Client.lambda$new$0(RestAnalyticsProvider.java:455)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider$Client.lambda$new$0(RestAnalyticsProvider.java:455)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.execute(RestAnalyticsProvider.java:390)
	... 32 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
	... 61 more

**Comment by shalom938** [comment]
Unhandled exception in [CoroutineId(14496), "coroutine#14496":StandaloneCoroutine{Cancelling}@12b76f, Dispatchers.Default]

org.digma.intellij.plugin.analytics.AnalyticsServiceException: An AnalyticsProviderException was caught
	at org.digma.intellij.plugin.analytics.AnalyticsService.executeCatching(AnalyticsService.java:539)
	at org.digma.intellij.plugin.analytics.AnalyticsService.getVersions(AnalyticsService.java:307)
	at org.digma.intellij.plugin.updates.UpdatesService.checkForNewerVersions(UpdatesService.kt:122)
	at org.digma.intellij.plugin.updates.UpdatesService.access$checkForNewerVersions(UpdatesService.kt:34)
	at org.digma.intellij.plugin.updates.UpdatesService$3$1.invokeSuspend(UpdatesService.kt:107)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineId(14496), "coroutine#14496":StandaloneCoroutine{Cancelled}@12b76f, Dispatchers.Default]
Caused by: org.digma.intellij.plugin.analytics.AnalyticsProviderException: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:5051
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.execute(RestAnalyticsProvider.java:392)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.getVersions(RestAnalyticsProvider.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.digma.intellij.plugin.auth.AuthManager$MyAuthInvocationHandler.invoke(AuthManager.kt:470)
	at jdk.proxy7/jdk.proxy7.$Proxy119.getVersions(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.digma.intellij.plugin.analytics.AnalyticsService$AnalyticsInvocationHandler.invoke(AnalyticsService.java:624)
	at jdk.proxy7/jdk.proxy7.$Proxy119.getVersions(Unknown Source)
	at org.digma.intellij.plugin.analytics.AnalyticsService.lambda$getVersions$17(AnalyticsService.java:307)
	at org.digma.intellij.plugin.analytics.AnalyticsService.executeCatching(AnalyticsService.java:537)
	... 10 more
Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:5051
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:223)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider$Client.lambda$new$0(RestAnalyticsProvider.java:455)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider$Client.lambda$new$0(RestAnalyticsProvider.java:455)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at org.digma.intellij.plugin.analytics.RestAnalyticsProvider.execute(RestAnalyticsProvider.java:390)
	... 25 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
	... 54 more
