### ISSUE TITLE
Cannot invoke (class=, method=environmentChanged, topic=ENVIRONMENT_CHANGED_TOPIC)

### ISSUE THREAD

**Issue by asafchen-dig** [digma-ai/digma-intellij-plugin#2257]
https://us.posthog.com/project/22368/events/87fbb994-d303-4924-bc02-4ba6ad3d46a9/2024-07-04T00%3A47%3A51.979000-07%3A00

``` java
java.lang.RuntimeException: Cannot invoke (class=, method=environmentChanged, topic=ENVIRONMENT_CHANGED_TOPIC) 
at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:677) 
at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:423) 
at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:402) 
at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1) 
at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:461) 
at jdk.proxy19/jdk.proxy19.$Proxy183.environmentChanged(Unknown Source) 
at org.digma.intellij.plugin.analytics.Environment.lambda$notifyEnvironmentChanged$6(Environment.java:254) 
at org.digma.intellij.plugin.common.Backgroundable.runWithErrorReporting(Backgroundable.java:122) 
at org.digma.intellij.plugin.common.Backgroundable$3.run(Backgroundable.java:68) 
at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477) 
at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133) 
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528) 
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250) 
at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100) 
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221) 
at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:46) 
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220) 
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660) 
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735) 
at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691) 
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659) 
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79) 
at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202) 
at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100) 
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250) 
at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:500) 
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) 
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) 
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702) 
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699) 
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) 
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699) 
at java.base/java.lang.Thread.run(Thread.java:840) Suppressed: java.lang.RuntimeException: Cannot invoke (class=, method=environmentChanged, topic=ENVIRONMENT_CHANGED_TOPIC) ... 33 more Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method org.digma.intellij.plugin.ui.recentactivity.RecentActivityUpdater$1.environmentChanged, parameter newEnv 
at org.digma.intellij.plugin.ui.recentactivity.RecentActivityUpdater$1.environmentChanged(RecentActivityUpdater.kt) 
at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700) 
at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:660) ... 32 more Suppressed: java.lang.RuntimeException: Cannot invoke (class=, method=environmentChanged, topic=ENVIRONMENT_CHANGED_TOPIC) ... 33 more Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method org.digma.intellij.plugin.ui.jcef.JCefComponent$11.environmentChanged, parameter newEnv 
at org.digma.intellij.plugin.ui.jcef.JCefComponent$11.environmentChanged(JCefComponent.kt) 
at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700) 
at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:660) ... 32 more Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method org.digma.intellij.plugin.ui.jcef.JCefComponent$11.environmentChanged, parameter newEnv 
at org.digma.intellij.plugin.ui.jcef.JCefComponent$11.environmentChanged(JCefComponent.kt) 
at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700) 
at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:660) ... 32 more
```java.lang.RuntimeException: Cannot invoke (class=, method=environmentChanged, topic=ENVIRONMENT_CHANGED_TOPIC) 
at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:677) 
at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:423) 
at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:402) 
at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1) 
at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:461) 
at jdk.proxy19/jdk.proxy19.$Proxy183.environmentChanged(Unknown Source) 
at org.digma.intellij.plugin.analytics.Environment.lambda$notifyEnvironmentChanged$6(Environment.java:254) 
at org.digma.intellij.plugin.common.Backgroundable.runWithErrorReporting(Backgroundable.java:122) 
at org.digma.intellij.plugin.common.Backgroundable$3.run(Backgroundable.java:68) 
at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477) 
at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133) 
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528) 
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250) 
at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100) 
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221) 
at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:46) 
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220) 
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660) 
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735) 
at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691) 
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659) 
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79) 
at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202) 
at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100) 
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250) 
at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:500) 
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) 
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) 
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702) 
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699) 
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) 
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699) 
at java.base/java.lang.Thread.run(Thread.java:840) Suppressed: java.lang.RuntimeException: Cannot invoke (class=, method=environmentChanged, topic=ENVIRONMENT_CHANGED_TOPIC) ... 33 more Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method org.digma.intellij.plugin.ui.recentactivity.RecentActivityUpdater$1.environmentChanged, parameter newEnv 
at org.digma.intellij.plugin.ui.recentactivity.RecentActivityUpdater$1.environmentChanged(RecentActivityUpdater.kt) 
at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700) 
at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:660) ... 32 more Suppressed: java.lang.RuntimeException: Cannot invoke (class=, method=environmentChanged, topic=ENVIRONMENT_CHANGED_TOPIC) ... 33 more Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method org.digma.intellij.plugin.ui.jcef.JCefComponent$11.environmentChanged, parameter newEnv 
at org.digma.intellij.plugin.ui.jcef.JCefComponent$11.environmentChanged(JCefComponent.kt) 
at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700) 
at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:660) ... 32 more Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method org.digma.intellij.plugin.ui.jcef.JCefComponent$11.environmentChanged, parameter newEnv 
at org.digma.intellij.plugin.ui.jcef.JCefComponent$11.environmentChanged(JCefComponent.kt) 
at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700) 
at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:660) ... 32 more

**Comment by shalom938** [comment]
This looks to me like one of these cases that we try to query the psi and the index is currently changing or changed very recently and the psi index throws exceptions.
we have a task to try pause querying the index in certain events
