### ISSUE TITLE
No ID found for serializer java.FILE

### ISSUE THREAD

**Issue by asafchen-dig** [digma-ai/digma-intellij-plugin#2258]
https://us.posthog.com/project/22368/events/698ebb40-2a99-4030-929d-024960fe0d12/2024-07-02T01%3A05%3A12.012000-07%3A00

``` java
java.lang.AssertionError: No ID found for serializer java.FILE (com.intellij.psi.impl.source.JavaFileElementType), external id:java.FILE, language:Language: JAVA 
at com.intellij.psi.stubs.StubSerializerEnumerator.getClassId(StubSerializerEnumerator.java:78) 
at com.intellij.psi.stubs.StubSerializationHelper.writeSerializerId(StubSerializationHelper.java:37) 
at com.intellij.psi.stubs.StubSerializationHelper.writeSerializerId(StubSerializationHelper.java:12) 
at com.intellij.psi.stubs.StubTreeSerializerBase.writeSerializerId(StubTreeSerializerBase.java:149) 
at com.intellij.psi.stubs.StubTreeSerializerBase.serializeSelf(StubTreeSerializerBase.java:140) 
at com.intellij.psi.stubs.StubTreeSerializerBase.serializeRoot(StubTreeSerializerBase.java:169) 
at com.intellij.psi.stubs.StubTreeSerializerBase.serialize(StubTreeSerializerBase.java:86) 
at com.intellij.psi.stubs.SerializationManagerImpl.serialize(SerializationManagerImpl.java:199) 
at com.intellij.psi.stubs.SerializedStubTree.serializeStub(SerializedStubTree.java:98) 
at com.intellij.psi.stubs.StubUpdatingIndex$2.computeValue(StubUpdatingIndex.java:212) 
at com.intellij.psi.stubs.StubUpdatingIndex$2.computeValue(StubUpdatingIndex.java:176) 
at com.intellij.psi.stubs.StubUpdatingIndex$2.computeValue(StubUpdatingIndex.java:145) 
at com.intellij.util.indexing.SingleEntryIndexer.map(SingleEntryIndexer.java:30) 
at com.intellij.util.indexing.SingleEntryIndexer.map(SingleEntryIndexer.java:19) 
at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:318) 
at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:309) 
at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:254) 
at com.intellij.psi.stubs.StubUpdatingIndexStorage.mapInputAndPrepareUpdate(StubUpdatingIndexStorage.java:62) 
at com.intellij.psi.stubs.StubUpdatingIndexStorage.mapInputAndPrepareUpdate(StubUpdatingIndexStorage.java:22) 
at com.intellij.indexing.composite.CompositeInvertedIndexBase.updateBaseIndex(CompositeInvertedIndexBase.java:286) 
at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:63) 
at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:29) 
at com.intellij.util.indexing.FileBasedIndexImpl.createSingleIndexValueApplier(FileBasedIndexImpl.java:1590) 
at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$22(FileBasedIndexImpl.java:1460) 
at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.lambda$freezeFileTypeTemporarilyWithProvidedValueIn$15(FileTypeManagerImpl.java:731) 
at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:795) 
at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyWithProvidedValueIn(FileTypeManagerImpl.java:727) 
at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1413) 
at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1387) 
at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1332) 
at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1701) 
at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1695) 
at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:63) 
at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:32) 
at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1718) 
at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:810) 
at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:358) 
at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:168) 
at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:102) 
at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:90) 
at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.getClasses(JavaFullClassNameIndex.java:37) 
at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:82) 
at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:105) 
at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:40) 
at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:95) 
at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:73) 
at org.digma.intellij.plugin.idea.psi.PsiPointers.getPsiClassPointer$lambda$2(PsiPointers.kt:32) 
at com.intellij.openapi.project.DumbService.runReadActionInSmartMode$lambda$0(DumbService.kt:84) 
at com.intellij.openapi.project.DumbService.runReadActionInSmartMode$lambda$2(DumbService.kt:136) 
at com.intellij.openapi.application.impl.RwLockHolder.runReadAction(RwLockHolder.kt:289) 
at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:850) 
at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65) 
at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.kt:129) 
at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.kt:84) 
at org.digma.intellij.plugin.common.PsiAccessUtilsKt.runInReadAccessInSmartModeWithResultAndRetryIgnorePCE$lambda$5(PsiAccessUtils.kt:65) 
at org.digma.intellij.plugin.common.RetryUtilsKt.runWIthRetryWithResultIgnorePCE(RetryUtils.kt:81) 
at org.digma.intellij.plugin.common.RetryUtilsKt.runWIthRetryWithResultIgnorePCE$default(RetryUtils.kt:70) 
at org.digma.intellij.plugin.common.PsiAccessUtilsKt.runInReadAccessInSmartModeWithResultAndRetryIgnorePCE(PsiAccessUtils.kt:61) 
at org.digma.intellij.plugin.idea.psi.PsiPointers.getPsiClassPointer(PsiPointers.kt:31) 
at org.digma.intellij.plugin.idea.psi.PsiPointers.getPsiClass(PsiPointers.kt:25) 
at org.digma.intellij.plugin.idea.psi.discovery.endpoint.SpringBootFrameworkEndpointDiscovery.getControllerAnnotationClass(SpringBootFrameworkEndpointDiscovery.kt:65) 
at org.digma.intellij.plugin.idea.psi.discovery.endpoint.SpringBootFrameworkEndpointDiscovery.isSpringBootWebRelevant(SpringBootFrameworkEndpointDiscovery.kt:70) 
at org.digma.intellij.plugin.idea.psi.discovery.endpoint.SpringBootFrameworkEndpointDiscovery.lookForEndpoints(SpringBootFrameworkEndpointDiscovery.kt:76) 
at org.digma.intellij.plugin.idea.navigation.JvmEndpointNavigationProvider.buildEndpointNavigation$lambda$3$lambda$2(JvmEndpointNavigationProvider.kt:68) 
at org.digma.intellij.plugin.idea.navigation.NavigationUtilsKt.executeCatchingWithRetry$lambda$1$lambda$0(navigationUtils.kt:17) 
at org.digma.intellij.plugin.common.RetryUtilsKt.runWIthRetryIgnorePCE(RetryUtils.kt:55) 
at org.digma.intellij.plugin.common.RetryUtilsKt.runWIthRetryIgnorePCE$default(RetryUtils.kt:45) 
at org.digma.intellij.plugin.idea.navigation.NavigationUtilsKt.executeCatchingWithRetry$lambda$1(navigationUtils.kt:16) 
at org.digma.intellij.plugin.common.CatchingUtilsKt.executeCatchingIgnorePCE(CatchingUtils.kt:51) 
at org.digma.intellij.plugin.common.CatchingUtilsKt.executeCatchingIgnorePCE$default(CatchingUtils.kt:49) 
at org.digma.intellij.plugin.idea.navigation.NavigationUtilsKt.executeCatchingWithRetry(navigationUtils.kt:15) 
at org.digma.intellij.plugin.idea.navigation.JvmEndpointNavigationProvider.buildEndpointNavigation(JvmEndpointNavigationProvider.kt:67) 
at org.digma.intellij.plugin.idea.navigation.JvmEndpointNavigationProvider.getTask$lambda$0(JvmEndpointNavigationProvider.kt:47) 
at org.digma.intellij.plugin.idea.navigation.AbstractNavigationDiscovery.buildNavigationUnderProgress$lambda$2(AbstractNavigationDiscovery.kt:117) 
at org.digma.intellij.plugin.progress.InvisibleRetryableTask.run$lambda$0(InvisibleRetryableTask.kt:33) 
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:217) 
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660) 
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735) 
at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691) 
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659) 
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79) 
at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202) 
at org.digma.intellij.plugin.progress.InvisibleRetryableTask.run(InvisibleRetryableTask.kt:32) 
at org.digma.intellij.plugin.progress.ProgressUtilsKt.runInvisibleBackgroundTaskInProgressWithRetry$lambda$0(ProgressUtils.kt:22) 
at org.digma.intellij.plugin.common.Backgroundable.runWithErrorReporting(Backgroundable.java:131) 
at org.digma.intellij.plugin.common.Backgroundable.ensurePooledThreadWithoutReadAccess(Backgroundable.java:87) 
at org.digma.intellij.plugin.progress.ProgressUtilsKt.runInvisibleBackgroundTaskInProgressWithRetry(ProgressUtils.kt:21) 
at org.digma.intellij.plugin.progress.RetryableTask$Invisible.runInBackground(RetryableTask.kt:121) 
at org.digma.intellij.plugin.idea.navigation.AbstractNavigationDiscovery.buildNavigationUnderProgress(AbstractNavigationDiscovery.kt:195) 
at org.digma.intellij.plugin.idea.navigation.AbstractNavigationDiscovery.schedule$lambda$1(AbstractNavigationDiscovery.kt:99) 
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) 
at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32) 
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) 
at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272) 
at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:244) 
at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30) 
at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:222) 
at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218) 
at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210) 
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) 
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) 
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702) 
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699) 
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) 
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699) 
at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by shalom938** [comment]
Nothing to fix, probably corrupted index.
