### ISSUE TITLE
Caused by: java.lang.OutOfMemoryError: Java heap space (f32eb575)

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#2284]
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor672.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.digma.intellij.plugin.analytics.AnalyticsService$AnalyticsInvocationHandler.invoke(AnalyticsService.java:629)
	at jdk.proxy10/jdk.proxy10.$Proxy170.getEnvironments(Unknown Source)
	at org.digma.intellij.plugin.analytics.AnalyticsService.lambda$getEnvironments$2(AnalyticsService.java:168)
	at org.digma.intellij.plugin.analytics.AnalyticsService.executeCatching(AnalyticsService.java:543)
	at org.digma.intellij.plugin.analytics.AnalyticsService.getEnvironments(AnalyticsService.java:168)
	at org.digma.intellij.plugin.analytics.Environment.refreshEnvironments(Environment.java:143)
	at org.digma.intellij.plugin.analytics.Environment.lambda$refreshNowOnBackground$1(Environment.java:118)
	at org.digma.intellij.plugin.common.Backgroundable.runWithErrorReporting(Backgroundable.java:122)
	at org.digma.intellij.plugin.common.Backgroundable.ensureBackgroundWithoutReadAccess(Backgroundable.java:56)
	at org.digma.intellij.plugin.analytics.Environment.refreshNowOnBackground(Environment.java:114)
	at org.digma.intellij.plugin.analytics.EnvironmentRefreshSchedulerKt$scheduleEnvironmentRefresh$1.invokeSuspend(EnvironmentRefreshScheduler.kt:17)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at jdk.proxy10/jdk.proxy10.$Proxy170.getEnvironments(Unknown Source)
	... 20 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor672.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.digma.intellij.plugin.auth.AuthManager$MyAuthInvocationHandler.invoke(AuthManager.kt:217)
	... 21 more
Caused by: java.lang.OutOfMemoryError: Java heap space

**Comment by shalom938** [comment]
there is no indication that the OOM is a result of our plugin
