### ISSUE TITLE
Error - Access is allowed from event dispatch thread only

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#283]
STR

**Having** some changes in files in a specific branch
**When** I rollback all the changes and checkout from main branch
**Then** error occurred
please see the following error:

Access is allowed from event dispatch thread only

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false
Current thread: Thread[ApplicationImpl pooled thread 418,4,main] 1389399099
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 921169057
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1110)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1093)
	at com.intellij.ide.IdeEventQueue.lambda$new$2(IdeEventQueue.java:205)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:336)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at java.desktop/java.awt.KeyboardFocusManager.firePropertyChange(KeyboardFocusManager.java:1501)
	at java.desktop/java.awt.KeyboardFocusManager.setGlobalPermanentFocusOwner(KeyboardFocusManager.java:796)
	at java.desktop/java.awt.Component.removeNotify(Component.java:7143)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2851)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4865)
	at java.desktop/javax.swing.AbstractButton.removeNotify(AbstractButton.java:1004)
	at java.desktop/javax.swing.JButton.removeNotify(JButton.java:230)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2835)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4865)
	at java.desktop/java.awt.Container.remove(Container.java:1235)
	at java.desktop/java.awt.Container.remove(Container.java:1293)
	at org.digma.intellij.plugin.ui.common.EnvironmentsPanel.rebuild(EnvironmentsPanel.kt:174)
	at org.digma.intellij.plugin.ui.common.EnvironmentsPanel.rebuildInBackground$lambda-4(EnvironmentsPanel.kt:161)
	at org.digma.intellij.plugin.common.Backgroundable$1.run(Backgroundable.java:29)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.codeWithMe.ClientId$Companion$decorateFunction$2.apply(ClientId.kt:307)
	at com.intellij.codeWithMe.ClientId$Companion$decorateFunction$2.apply(ClientId.kt:307)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by MykolaYaremchuk** [comment]
this issue will be fixed in scope of Release `v2.0.22` (`v1.0.73`)
