### ISSUE TITLE
pycharm - issues

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#335]
span discovery

- validate_group_exists missing insights
span_code_object_id: span:database_validation$_$check_db_permission

- no insights in database_validation.py

Errors Tab

- by clicking on error item the following error occurred:
java.lang.StringIndexOutOfBoundsException: begin -1, end 125, length 125
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4604)
	at java.base/java.lang.String.substring(String.java:2707)
	at java.base/java.lang.String.substring(String.java:2680)
	at org.digma.intellij.plugin.pycharm.psi.python.PythonLanguageUtils.buildFilePath(PythonLanguageUtils.java:23)
	at org.digma.intellij.plugin.pycharm.psi.python.PythonLanguageUtils.createPythonMethodCodeObjectId(PythonLanguageUtils.java:15)
	at org.digma.intellij.plugin.pycharm.psi.python.PythonLanguageService.lambda$findWorkspaceUrisForCodeObjectIds$1(PythonLanguageService.java:171)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.digma.intellij.plugin.pycharm.psi.python.PythonLanguageService.findWorkspaceUrisForCodeObjectIds(PythonLanguageService.java:163)
	at org.digma.intellij.plugin.errors.ErrorsProvider.findWorkspaceUriForFrames(ErrorsProvider.java:159)
	at org.digma.intellij.plugin.errors.ErrorsProvider.buildFlowStack(ErrorsProvider.java:117)
	at org.digma.intellij.plugin.errors.ErrorsProvider.lambda$buildFlowStacks$1(ErrorsProvider.java:109)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.digma.intellij.plugin.errors.ErrorsProvider.buildFlowStacks(ErrorsProvider.java:108)
	at org.digma.intellij.plugin.errors.ErrorsProvider.getErrorDetails(ErrorsProvider.java:98)
	at org.digma.intellij.plugin.ui.service.ErrorsViewService.showErrorDetails(ErrorsViewService.kt:88)
	at org.digma.intellij.plugin.service.ErrorsActionsService.showErrorDetails(ErrorsActionsService.java:47)
	at org.digma.intellij.plugin.service.ErrorsActionsService.showErrorDetails(ErrorsActionsService.java:41)
	at org.digma.intellij.plugin.ui.list.errors.ErrorsPanelListCellRendererKt$createSingleErrorPanel$link$1.invoke(ErrorsPanelListCellRenderer.kt:52)
	at org.digma.intellij.plugin.ui.list.errors.ErrorsPanelListCellRendererKt$createSingleErrorPanel$link$1.invoke(ErrorsPanelListCellRenderer.kt:50)
	at com.intellij.ui.components.ActionLink._init_$lambda$1(ActionLink.kt:36)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by shalom938** [comment]
I don't see that the span id is missing, database_validation$_$check_db_permission exists and sent with related ids

**Comment by shalom938** [comment]
The StringIndexOutOfBoundsException is fixed
