### ISSUE TITLE
SlowEndpoint insight error

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#351]
java.lang.NumberFormatException: Infinite or NaN
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:985)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:964)
	at org.digma.intellij.plugin.ui.list.insights.SlowEndpointPanelKt.computePercentageDiff(SlowEndpointPanel.kt:55)
	at org.digma.intellij.plugin.ui.list.insights.SlowEndpointPanelKt.computePercentageDiff(SlowEndpointPanel.kt:50)
	at org.digma.intellij.plugin.ui.list.insights.SlowEndpointPanelKt.genContent(SlowEndpointPanel.kt:45)
	at org.digma.intellij.plugin.ui.list.insights.SlowEndpointPanelKt.slowEndpointPanel(SlowEndpointPanel.kt:16)
	at org.digma.intellij.plugin.ui.list.insights.InsightsListCellRenderer.getOrCreatePanel(InsightsListCellRenderer.kt:46)
	at org.digma.intellij.plugin.ui.list.insights.InsightsListCellRenderer.createPanel(InsightsListCellRenderer.kt:30)
	at org.digma.intellij.plugin.ui.list.AbstractPanelListCellRenderer.getListCellRendererComponent(AbstractPanelListCellRenderer.kt:24)
	at org.digma.intellij.plugin.ui.list.PanelList.rebuild(PanelList.kt:102)
	at org.digma.intellij.plugin.ui.list.PanelList.contentsChanged(PanelList.kt:144)
	at java.desktop/javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:127)
	at org.digma.intellij.plugin.ui.list.AbstractPanelListModel.setListData(AbstractPanelListModel.kt:22)
	at org.digma.intellij.plugin.ui.list.insights.InsightsList$MyModel.setListData(InsightsList.kt:47)
	at org.digma.intellij.plugin.ui.insights.InsightsTabKt$insightsPanel$result$1.reset(InsightsTab.kt:98)
	at org.digma.intellij.plugin.ui.common.NoConnectionWrapper.reset(NoConnectionWrapper.kt:119)
	at org.digma.intellij.plugin.ui.service.AbstractViewService.doUpdateUi$lambda$3(AbstractViewService.kt:125)
	at org.digma.intellij.plugin.ui.service.AbstractViewService.doUpdateUi$lambda$4(AbstractViewService.kt:142)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by shaykeren** [comment]
@asafchen-dig can you please check if this one is related to the backend, should we add a check in the client side?

**Comment by asafchen-dig** [comment]
I couldn't find the reason in the BE, but I'm adding a log to get more info the next time it happens.

@MykolaYaremchuk, please add a check so the client won't fail on this - until we'll find the root cause.
