### ISSUE TITLE
Exception in plugin

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#471]
java.lang.IndexOutOfBoundsException: Collection doesn’t contain element at index 2.
	at kotlin.collections.CollectionsKt___CollectionsKt$elementAt$1.invoke(_Collections.kt:87)
	at kotlin.collections.CollectionsKt___CollectionsKt$elementAt$1.invoke(_Collections.kt:87)
	at kotlin.collections.CollectionsKt___CollectionsKt.elementAtOrElse(_Collections.kt:117)
	at kotlin.collections.CollectionsKt___CollectionsKt.elementAt(_Collections.kt:87)
	at org.digma.intellij.plugin.ui.common.EnvironmentsDropdownPanel$buildEnvironmentsDropdownPanelComponents$1.customize(EnvironmentsDropdownPanel.kt:204)
	at org.digma.intellij.plugin.ui.common.EnvironmentsDropdownPanel$buildEnvironmentsDropdownPanelComponents$1.customize(EnvironmentsDropdownPanel.kt:200)
	at com.intellij.ui.SimpleListCellRenderer.getListCellRendererComponent(SimpleListCellRenderer.java:65)
	at com.intellij.openapi.ui.ComboBoxWithWidePopup$AdjustingListCellRenderer.getListCellRendererComponent(ComboBoxWithWidePopup.java:85)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaComboBoxUI$CustomComboPopup$MyDelegateRenderer.getListCellRendererComponent(DarculaComboBoxUI.java:855)
	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:197)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1394)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2815)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:448)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:458)
	at java.desktop/javax.swing.DefaultListSelectionModel.removeSelectionIntervalImpl(DefaultListSelectionModel.java:619)
	at java.desktop/javax.swing.DefaultListSelectionModel.clearSelection(DefaultListSelectionModel.java:463)
	at java.desktop/javax.swing.JList.clearSelection(JList.java:2082)
	at java.desktop/javax.swing.JList.setModel(JList.java:1712)
	at java.desktop/javax.swing.plaf.basic.BasicComboPopup$Handler.propertyChange(BasicComboPopup.java:1054)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaComboBoxUI$CustomComboPopup$2.propertyChange(DarculaComboBoxUI.java:801)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8750)
	at java.desktop/javax.swing.JComboBox.setModel(JComboBox.java:362)
	at org.digma.intellij.plugin.ui.common.EnvironmentsDropdownPanel.buildEnvironmentsDropdownPanelComponents(EnvironmentsDropdownPanel.kt:194)
	at org.digma.intellij.plugin.ui.common.EnvironmentsDropdownPanel.rebuild$lambda$0(EnvironmentsDropdownPanel.kt:132)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by doppleware** [comment]
Happened to me twice
