### ISSUE TITLE
NullPointerException - beta user FRA

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#814]
java.lang.NullPointerException: method info com.finastra.fgpp.consolidator.ConsolidatorTest$_$whenTriggeringEventConsumed_1000_ConsolidationPaymentEvent_produced must exist in DocumentInfo for file://C:/infra/fgpp-consolidator/src/test/java/com/finastra/fgpp/consolidator/ConsolidatorTest.java
    at java.base/java.util.Objects.requireNonNull(Objects.java:233)
    at org.digma.intellij.plugin.idea.psi.java.JavaCodeObjectDiscovery.lambda$withSpanAnnotationSpanDiscovery$4(JavaCodeObjectDiscovery.java:186)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
    at org.digma.intellij.plugin.idea.psi.java.JavaCodeObjectDiscovery.lambda$withSpanAnnotationSpanDiscovery$5(JavaCodeObjectDiscovery.java:182)
    at java.base/java.lang.Iterable.forEach(Iterable.java:75)
    at org.digma.intellij.plugin.idea.psi.java.JavaCodeObjectDiscovery.withSpanAnnotationSpanDiscovery(JavaCodeObjectDiscovery.java:179)
    at org.digma.intellij.plugin.idea.psi.java.JavaCodeObjectDiscovery.spanDiscovery(JavaCodeObjectDiscovery.java:137)
    at org.digma.intellij.plugin.idea.psi.java.JavaCodeObjectDiscovery.enrichDocumentInfo(JavaCodeObjectDiscovery.java:131)
    at org.digma.intellij.plugin.idea.psi.java.JavaCodeObjectDiscovery.buildDocumentInfo(JavaCodeObjectDiscovery.java:59)
    at org.digma.intellij.plugin.idea.psi.java.JavaLanguageService.buildDocumentInfo(JavaLanguageService.java:461)
    at org.digma.intellij.plugin.idea.psi.java.JavaLanguageService.buildDocumentInfo(JavaLanguageService.java:470)
    at org.digma.intellij.plugin.editor.EditorEventsHandler.lambda$selectionChanged$0(EditorEventsHandler.java:159)
    at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
    at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:746)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:778)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:573)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:537)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1111)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:71)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:109)
    at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:68)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
    at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:68)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:106)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:71)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:537)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:444)
    at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
    at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
    at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
    at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:208)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
    at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by shaykeren** [comment]
duplicate #813
